### ISSUE TITLE
Unbundle RemmData from default data distribution

### ISSUE THREAD

**Issue by julesjacobsen** [exomiser/Exomiser#127]
For some people this is 13GB too much and they don't want it so this needs to be removed from the main data distribution.
- [x] Remove from main data zip file
- [x] Add to FTP site
- [x] Change the settings file to keep REMM with the CADD stuff - keep the value empty by default
- [ ] Update the README and Genomiser documentation

**Comment by damiansm** [comment]
Can this be closed now @julesjacobsen ?

**Comment by julesjacobsen** [comment]
Oops - still need to spell this out in the README. On a related not - did you not have some issues with tabix files silently not working or something?

**Comment by damiansm** [comment]
Yes - I had forgotten to define my Remm file path in application.properties
and added REMM as a source in the yml. The code silently ran ignoring the
Remm file that was sitting in the default location in my data directory!
Def needs fixing as took me a while to spot!

**Comment by julesjacobsen** [comment]
That was the one. Need to decide whether you want a logged warning, lots and lots of warnings and it carries on or logs an error and then completely falls over.

**Comment by damiansm** [comment]
Think it is best if it either exits with an error message that the file
path was not defined in application.properties or attempts to use a default
file in the data directory.

**Comment by julesjacobsen** [comment]
Given REMM, CADD and LOCAL are all optional, it's up to the user to ensure they have these options enabled. The Tabix reader requires a file to start-up with so it has an empty one by default otherwise the application won't start. So maybe the best solution would be that the application will start even if the file hasn't been defined, but if the used requests a data source which isn't present the application then logs an error and exits as soon as the data is requested?

**Comment by julesjacobsen** [comment]
Behaviour is now like this on start-up:
```
2017-07-20 14:43:53.286 [main] WARN  org.monarchinitiative.exomiser.autoconfigure.ExomiserAutoConfiguration - Data for REMM is not configured. THIS WILL LEAD TO ERRORS IF REQUIRED DURING ANALYSIS. Check the application.properties is pointing to a valid file.
```
but the application will continue to run.  However should one of the data sources be requested during an analysis e.g. REMM in this case, the application throws an error and quits:
```
Exception in thread "main" java.lang.IllegalArgumentException: Data for REMM is not configured. Check the application.properties is pointing to a valid file.
        at org.monarchinitiative.exomiser.core.genome.dao.ErrorThrowingTabixDataSource.query(ErrorThrowingTabixDataSource.java:21)
        at org.monarchinitiative.exomiser.core.genome.dao.RemmDao.getRemmData(RemmDao.java:107)
        at org.monarchinitiative.exomiser.core.genome.dao.RemmDao.processResults(RemmDao.java:69)
        at org.monarchinitiative.exomiser.core.genome.dao.RemmDao.getPathogenicityData(RemmDao.java:62)
```
