### ISSUE TITLE
Adding ESE Splice scores

### ISSUE THREAD

**Issue by visze** [exomiser/Exomiser#133]
The score of this publication (ESEseqs, https://doi.org/10.1101/gr.119628.110) defines splice scores of `MISSENSE`and `SYNONYMOUS` variants. 

Here is an implementation of the ESEseqs: https://github.com/charite/ESElator

We can integrate this to define this missing piece in Exomiser.

**Comment by julesjacobsen** [comment]
@visze Can you make it public or give me permission to see it please!

**Comment by visze** [comment]
@julesjacobsen it is public now. But still beta. I have to refactor the code a lot. But I tried to integrate it into exomiser. basically to learn a bit more the code. But I get an error and I do not know if this error is from my changes or it is because you refactorer the spring code:

```
2016-05-31 13:16:30.836 [main] WARN  org.springframework.context.annotation.AnnotationConfigApplicationContext - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'exomiserCommandLineRunner': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private de.charite.compbio.exomiser.core.analysis.AnalysisParser de.charite.compbio.exomiser.cli.ExomiserCommandLineRunner.analysisParser; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'analysisParser' defined in file [/home/mschubach/Exomiser/exomiser/exomiser-core/target/classes/de/charite/compbio/exomiser/core/analysis/AnalysisParser.class]: Unsatisfied dependency expressed through constructor argument with index 0 of type [de.charite.compbio.exomiser.core.prioritisers.PriorityFactory]: No qualifying bean of type [de.charite.compbio.exomiser.core.prioritisers.PriorityFactory] is defined: expected single matching bean but found 2: priorityFactoryImpl,priorityFactory; nested exception is org.springframework.beans.factory.NoUniqueBeanDefinitionException: No qualifying bean of type [de.charite.compbio.exomiser.core.prioritisers.PriorityFactory] is defined: expected single matching bean but found 2: priorityFactoryImpl,priorityFactory
Exception in thread "main" org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'exomiserCommandLineRunner': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private de.charite.compbio.exomiser.core.analysis.AnalysisParser de.charite.compbio.exomiser.cli.ExomiserCommandLineRunner.analysisParser; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'analysisParser' defined in file [/home/mschubach/Exomiser/exomiser/exomiser-core/target/classes/de/charite/compbio/exomiser/core/analysis/AnalysisParser.class]: Unsatisfied dependency expressed through constructor argument with index 0 of type [de.charite.compbio.exomiser.core.prioritisers.PriorityFactory]: No qualifying bean of type [de.charite.compbio.exomiser.core.prioritisers.PriorityFactory] is defined: expected single matching bean but found 2: priorityFactoryImpl,priorityFactory; nested exception is org.springframework.beans.factory.NoUniqueBeanDefinitionException: No qualifying bean of type [de.charite.compbio.exomiser.core.prioritisers.PriorityFactory] is defined: expected single matching bean but found 2: priorityFactoryImpl,priorityFactory
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:334)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1214)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:543)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:772)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:839)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:538)
	at org.springframework.context.annotation.AnnotationConfigApplicationContext.<init>(AnnotationConfigApplicationContext.java:84)
	at de.charite.compbio.exomiser.cli.Main.setUpApplicationContext(Main.java:61)
	at de.charite.compbio.exomiser.cli.Main.run(Main.java:50)
	at de.charite.compbio.exomiser.cli.Main.main(Main.java:46)
Caused by: org.springframework.beans.factory.BeanCreationException: Could not autowire field: private de.charite.compbio.exomiser.core.analysis.AnalysisParser de.charite.compbio.exomiser.cli.ExomiserCommandLineRunner.analysisParser; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'analysisParser' defined in file [/home/mschubach/Exomiser/exomiser/exomiser-core/target/classes/de/charite/compbio/exomiser/core/analysis/AnalysisParser.class]: Unsatisfied dependency expressed through constructor argument with index 0 of type [de.charite.compbio.exomiser.core.prioritisers.PriorityFactory]: No qualifying bean of type [de.charite.compbio.exomiser.core.prioritisers.PriorityFactory] is defined: expected single matching bean but found 2: priorityFactoryImpl,priorityFactory; nested exception is org.springframework.beans.factory.NoUniqueBeanDefinitionException: No qualifying bean of type [de.charite.compbio.exomiser.core.prioritisers.PriorityFactory] is defined: expected single matching bean but found 2: priorityFactoryImpl,priorityFactory
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:573)
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:88)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:331)
	... 14 more
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'analysisParser' defined in file [/home/mschubach/Exomiser/exomiser/exomiser-core/target/classes/de/charite/compbio/exomiser/core/analysis/AnalysisParser.class]: Unsatisfied dependency expressed through constructor argument with index 0 of type [de.charite.compbio.exomiser.core.prioritisers.PriorityFactory]: No qualifying bean of type [de.charite.compbio.exomiser.core.prioritisers.PriorityFactory] is defined: expected single matching bean but found 2: priorityFactoryImpl,priorityFactory; nested exception is org.springframework.beans.factory.NoUniqueBeanDefinitionException: No qualifying bean of type [de.charite.compbio.exomiser.core.prioritisers.PriorityFactory] is defined: expected single matching bean but found 2: priorityFactoryImpl,priorityFactory
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:749)
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:185)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1143)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1046)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:510)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.findAutowireCandidates(DefaultListableBeanFactory.java:1192)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1116)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1014)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:545)
	... 16 more
Caused by: org.springframework.beans.factory.NoUniqueBeanDefinitionException: No qualifying bean of type [de.charite.compbio.exomiser.core.prioritisers.PriorityFactory] is defined: expected single matching bean but found 2: priorityFactoryImpl,priorityFactory
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1126)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1014)
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:813)
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:741)
	... 29 more
```

**Comment by julesjacobsen** [comment]
I've no idea what you've done. Are you're trying to add this as a new Prioritiser?

**Comment by visze** [comment]
I have the same problem on the development code!

I added it as a new pathogenicity score.

**Comment by visze** [comment]
update: If I remove `@Component` before the `PriorityFactoryImpl` class the error is gone. 
@julesjacobsen Is  `@Component` important? Or should we add it only to the interface `PriorityFactory`?

**Comment by julesjacobsen** [comment]
@Component is a Spring annotation to enable the dependency injection. Don't remove it just to satisfy Eclipse!

**Comment by visze** [comment]
But what is the fix here? maybe there are problem because the class implements an interface?

Sorry I have no knowledge about spring

**Comment by julesjacobsen** [comment]
So are you trying to run this as a system test in the core module? I wanted to keep the core as DI neutral as possible (bar the obvious annotations). You can set-up an analysis manually building the components as normal using the Java classes and constructor injection mostly. i.e. with the AnalysisParser - just provide it with the implementations you want. See AnalysisParserTest and AnalysisRunnerTestBase for examples. It might be quicker to talk about this given I'm still not sure exactly how you're trying to test things.
