### ISSUE TITLE
Error when using local frequencies

### ISSUE THREAD

**Issue by garrett-stevens** [exomiser/Exomiser#223]
Hello,

I've been trying to add local frequencies to Exomiser following what I found in #157, but I'm getting an error. I am using the examples/test-analysis-exome.yml analysis file with "LOCAL" added to the `frequencySources` list. I also have the line `exomiser.local-frequency-path=${exomiser.data-directory}/test.tsv.gz` in my `application.properties` and a file called 'test.tsv.gz' with the accompanying `.tbi` index in the exomiser data directory. The `test.tsv.gz` file looks like this:
```
##Chromosome names: 1-22, X, Y, M
##Positions should be 1-based.
##REF/ALT deletions should have a '.' character in their place.
##Frequency column should be a percentage value i.e. range 0.0 - 100.0
##Multiple alternative alleles should be split so that each occurs on its own line.
#CHR    POS     REF     ALT     FREQ(%)
1       879317  C       T       8.2033
```
Here is the stack trace:
```
$ java -Xms2g -Xmx4g -jar exomiser-cli-8.0.0.jar --analysis examples/test-analysis-exome.yml
... # lines omitted
2017-08-11 22:20:12.722 [main] INFO  org.monarchinitiative.exomiser.core.genome.VariantFactory - Annotating variant records, trimming sequences and normalising positions...
2017-08-11 22:20:12.850 [main] INFO  org.monarchinitiative.exomiser.core.genome.VariantFactory - Processed 2 variant records into 2 single allele variants
2017-08-11 22:20:12.856 [main] INFO  org.monarchinitiative.exomiser.core.genome.VariantFactory - Variant annotation finished in 0m 0s 129ms (129 ms)
Exception in thread "main" java.lang.NumberFormatException: For input string: "8.2033"
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
        at java.lang.Integer.parseInt(Integer.java:580)
        at java.lang.Integer.parseInt(Integer.java:615)
        at htsjdk.tribble.readers.TabixReader.getIntv(TabixReader.java:300)
        at htsjdk.tribble.readers.TabixReader.access$400(TabixReader.java:46)
        at htsjdk.tribble.readers.TabixReader$IteratorImpl.next(TabixReader.java:394)
        at org.monarchinitiative.exomiser.core.genome.dao.LocalFrequencyDao.getPositionFrequencyData(LocalFrequencyDao.java:78)
        at org.monarchinitiative.exomiser.core.genome.dao.LocalFrequencyDao.processResults(LocalFrequencyDao.java:64)
        at org.monarchinitiative.exomiser.core.genome.dao.LocalFrequencyDao.getFrequencyData(LocalFrequencyDao.java:55)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:333)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
        at org.springframework.cache.interceptor.CacheInterceptor$1.invoke(CacheInterceptor.java:52)
        at org.springframework.cache.interceptor.CacheAspectSupport.invokeOperation(CacheAspectSupport.java:345)
        at org.springframework.cache.interceptor.CacheAspectSupport.execute(CacheAspectSupport.java:414)
        at org.springframework.cache.interceptor.CacheAspectSupport.execute(CacheAspectSupport.java:327)
        at org.springframework.cache.interceptor.CacheInterceptor.invoke(CacheInterceptor.java:61)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:213)
        at com.sun.proxy.$Proxy40.getFrequencyData(Unknown Source)
        at org.monarchinitiative.exomiser.core.genome.VariantDataServiceImpl.getVariantFrequencyData(VariantDataServiceImpl.java:79)
        at org.monarchinitiative.exomiser.core.filters.FrequencyDataProvider.provideVariantData(FrequencyDataProvider.java:56)
        at org.monarchinitiative.exomiser.core.filters.AbstractFilterDataProvider.runFilter(AbstractFilterDataProvider.java:68)
        at org.monarchinitiative.exomiser.core.filters.AbstractFilterDataProvider.runFilter(AbstractFilterDataProvider.java:36)
        at org.monarchinitiative.exomiser.core.filters.SimpleVariantFilterRunner.runFilterAndAddResult(SimpleVariantFilterRunner.java:84)
        at org.monarchinitiative.exomiser.core.filters.SimpleVariantFilterRunner.run(SimpleVariantFilterRunner.java:80)
        at org.monarchinitiative.exomiser.core.analysis.SparseAnalysisRunner.lambda$null$2(SparseAnalysisRunner.java:59)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
        at org.monarchinitiative.exomiser.core.analysis.SparseAnalysisRunner.lambda$runVariantFilters$3(SparseAnalysisRunner.java:59)
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174)
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.stream.ReferencePipeline$11$1.accept(ReferencePipeline.java:373)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.stream.ReferencePipeline$11$1.accept(ReferencePipeline.java:373)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
        at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:270)
        at java.util.stream.ReferencePipeline$11$1.accept(ReferencePipeline.java:373)
        at java.util.Iterator.forEachRemaining(Iterator.java:116)
        at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
        at org.monarchinitiative.exomiser.core.analysis.AbstractAnalysisRunner.loadAndFilterVariants(AbstractAnalysisRunner.java:173)
        at org.monarchinitiative.exomiser.core.analysis.AbstractAnalysisRunner.run(AbstractAnalysisRunner.java:115)
        at org.monarchinitiative.exomiser.core.Exomiser.run(Exomiser.java:61)
        at org.monarchinitiative.exomiser.cli.ExomiserCommandLineRunner.runAnalysisAndWriteResults(ExomiserCommandLineRunner.java:144)
        at org.monarchinitiative.exomiser.cli.ExomiserCommandLineRunner.runAnalysisFromScript(ExomiserCommandLineRunner.java:133)
        at org.monarchinitiative.exomiser.cli.ExomiserCommandLineRunner.runAnalyses(ExomiserCommandLineRunner.java:82)
        at org.monarchinitiative.exomiser.cli.ExomiserCommandLineRunner.run(ExomiserCommandLineRunner.java:76)
        at org.monarchinitiative.exomiser.cli.Main.runExomiser(Main.java:83)
        at org.monarchinitiative.exomiser.cli.Main.run(Main.java:53)
        at org.monarchinitiative.exomiser.cli.Main.main(Main.java:47)
```
I noticed something about an integer, so I tried changing the frequency to `8` instead of `8.2033` and that seemed to work, but I'd like decimal precision in the population frequency percentages if possible. Thanks for any insight.

**Comment by julesjacobsen** [comment]
You've not indexed your input file correctly. The column layout is not one of the tabix presets so using ```tabix -p vcf``` for example will cause tabix to throw errors.

You'll want to use ```tabix -s 1 -b 2 -e 2 -c '#' test.tsv.gz``` also the HTSJKD ```TabixReader``` needs to have a newline character at the end of every line, including the last line otherwise the last line won't be read.

**Comment by garrett-stevens** [comment]
Ah, I was missing the `-e 2` when I created my index. Everything seems to be working now. Thanks!
