### ISSUE TITLE
Exomiser 8.0.0 - Error during creation of HTML output

### ISSUE THREAD

**Issue by stanedav** [exomiser/Exomiser#239]
Hello, 

I am getting error during performing exomiser analysis with this command:
C:\exomiser\exomiser-cli-8.0.0>java -Xms8g -Xmx16g -jar exomiser-cli-8.0.0.jar -
-prioritiser hiphive -I AD -F 1 --hpo-ids HP:0009830,HP:0000763 -v vcf/824.vcf -
f HTML

Error:
2017-12-11 09:26:54.465 [main] ERROR org.thymeleaf.TemplateEngine - [THYMELEAF][
main] Exception processing template "results": Error during creation of output
Exception in thread "main" org.thymeleaf.exceptions.TemplateOutputException: Err
or during creation of output
        at org.thymeleaf.TemplateEngine.process(TemplateEngine.java:1177)
        at org.thymeleaf.TemplateEngine.process(TemplateEngine.java:1060)
        at org.thymeleaf.TemplateEngine.process(TemplateEngine.java:1011)
        at org.thymeleaf.TemplateEngine.process(TemplateEngine.java:955)
        at org.monarchinitiative.exomiser.core.writers.HtmlResultsWriter.writeFi
le(HtmlResultsWriter.java:75)
        at org.monarchinitiative.exomiser.cli.ExomiserCommandLineRunner.writeRes
ults(ExomiserCommandLineRunner.java:152)
        at org.monarchinitiative.exomiser.cli.ExomiserCommandLineRunner.runAnaly
sisAndWriteResults(ExomiserCommandLineRunner.java:145)
        at org.monarchinitiative.exomiser.cli.ExomiserCommandLineRunner.runAnaly
sisFromSettings(ExomiserCommandLineRunner.java:139)
        at org.monarchinitiative.exomiser.cli.ExomiserCommandLineRunner.runAnaly
ses(ExomiserCommandLineRunner.java:109)
        at org.monarchinitiative.exomiser.cli.ExomiserCommandLineRunner.run(Exom
iserCommandLineRunner.java:76)
        at org.monarchinitiative.exomiser.cli.Main.runExomiser(Main.java:83)
        at org.monarchinitiative.exomiser.cli.Main.run(Main.java:53)
        at org.monarchinitiative.exomiser.cli.Main.main(Main.java:47)
        Suppressed: java.nio.charset.UnmappableCharacterException: Input length
= 1
                at java.nio.charset.CoderResult.throwException(Unknown Source)
                at sun.nio.cs.StreamEncoder.implWrite(Unknown Source)
                at sun.nio.cs.StreamEncoder.write(Unknown Source)
                at java.io.OutputStreamWriter.write(Unknown Source)
                at java.io.BufferedWriter.flushBuffer(Unknown Source)
                at java.io.BufferedWriter.close(Unknown Source)
                at org.monarchinitiative.exomiser.core.writers.HtmlResultsWriter
.writeFile(HtmlResultsWriter.java:76)
                ... 8 more
Caused by: java.nio.charset.UnmappableCharacterException: Input length = 1
        at java.nio.charset.CoderResult.throwException(Unknown Source)
        at sun.nio.cs.StreamEncoder.implWrite(Unknown Source)
        at sun.nio.cs.StreamEncoder.write(Unknown Source)
        at java.io.OutputStreamWriter.write(Unknown Source)
        at java.io.BufferedWriter.flushBuffer(Unknown Source)
        at java.io.BufferedWriter.write(Unknown Source)
        at java.io.Writer.write(Unknown Source)
        at org.thymeleaf.templatewriter.AbstractGeneralTemplateWriter.writeText(
AbstractGeneralTemplateWriter.java:326)
        at org.thymeleaf.templatewriter.AbstractGeneralTemplateWriter.writeNode(
AbstractGeneralTemplateWriter.java:149)
        at org.thymeleaf.templatewriter.AbstractGeneralTemplateWriter.writeEleme
nt(AbstractGeneralTemplateWriter.java:257)
        at org.thymeleaf.templatewriter.AbstractGeneralTemplateWriter.writeNode(
AbstractGeneralTemplateWriter.java:145)
        at org.thymeleaf.templatewriter.AbstractGeneralTemplateWriter.writeEleme
nt(AbstractGeneralTemplateWriter.java:257)
        at org.thymeleaf.templatewriter.AbstractGeneralTemplateWriter.writeNode(
AbstractGeneralTemplateWriter.java:145)
        at org.thymeleaf.templatewriter.AbstractGeneralTemplateWriter.writeEleme
nt(AbstractGeneralTemplateWriter.java:257)
        at org.thymeleaf.templatewriter.AbstractGeneralTemplateWriter.writeNode(
AbstractGeneralTemplateWriter.java:145)
        at org.thymeleaf.templatewriter.AbstractGeneralTemplateWriter.writeEleme
nt(AbstractGeneralTemplateWriter.java:257)
        at org.thymeleaf.templatewriter.AbstractGeneralTemplateWriter.writeNode(
AbstractGeneralTemplateWriter.java:145)
        at org.thymeleaf.templatewriter.AbstractGeneralTemplateWriter.writeEleme
nt(AbstractGeneralTemplateWriter.java:257)
        at org.thymeleaf.templatewriter.AbstractGeneralTemplateWriter.writeNode(
AbstractGeneralTemplateWriter.java:145)
        at org.thymeleaf.templatewriter.AbstractGeneralTemplateWriter.writeEleme
nt(AbstractGeneralTemplateWriter.java:257)
        at org.thymeleaf.templatewriter.AbstractGeneralTemplateWriter.writeNode(
AbstractGeneralTemplateWriter.java:145)
        at org.thymeleaf.templatewriter.AbstractGeneralTemplateWriter.writeDocum
ent(AbstractGeneralTemplateWriter.java:97)
        at org.thymeleaf.templatewriter.AbstractGeneralTemplateWriter.write(Abst
ractGeneralTemplateWriter.java:72)
        at org.thymeleaf.TemplateEngine.process(TemplateEngine.java:1175)
        ... 12 more

I tried previous version 7.2.1. where same commands works even with HTML as output. If I change HTML to VCF, then everything works ok.

**Comment by julesjacobsen** [comment]
Hi, sorry I've neglected this - this duplicates issue #243 - can you try running the job again using the parameters here:

https://github.com/exomiser/Exomiser/issues/243#issuecomment-358929915

**Comment by julesjacobsen** [comment]
Fixed in release 10.0.0.
