### ISSUE TITLE
I cann't get the HTML output test the  java -jar -Xmx16g -Djava.io.tmpdir=./tmp -jar  exomiser-cli-9.0.1.jar --analysis examples/test-analysis-exome.yml

### ISSUE THREAD

**Issue by kkshaxqd** [exomiser/Exomiser#243]
Hello:

When I use the examples follow the read.me , the run had a error like these:

2018-01-18 08:57:05.520 [main] ERROR org.thymeleaf.TemplateEngine - [THYMELEAF][main] Exception processing template "results": Error during creation of output
Error starting ApplicationContext. To display the auto-configuration report re-run your application with 'debug' enabled.
2018-01-18 08:57:05.544 [main] ERROR org.springframework.boot.SpringApplication - Application startup failed

and I cannot get the HTML out ,but set the vcf or TSV-GENE, TSV-VARIANT will OK .  So what's the reason and how can  I resolve it!

**Comment by julesjacobsen** [comment]
Was this running the exomiser from the application's home directory e.g. ```/opt/exomiser-cli-9.0.1/``` and using the command ```java -jar exomiser-cli-9.0.1.jar --analysis examples/test-analysis-exome.yml```? Does this also happen with an older distribution? 

Can you attach the log output for the run which failed? There might be a locale issue with the input VCF perhaps?

**Comment by kkshaxqd** [comment]
OK, thanks,  I run the exomiser in the home directory,  it work well when set the output is VCF or TSV-GENE or TSV-VARIANT, only the HTML cann't get the results.
this is the run log.

**2018-01-19 00:38:10.861 [main] INFO  org.monarchinitiative.exomiser.core.prioritisers.util.HiPhiveProteinInteractionScorer - Original data matrix (12511 rows * 12511 columns)
2018-01-19 00:38:10.916 [main] INFO  org.monarchinitiative.exomiser.core.prioritisers.util.HiPhiveProteinInteractionScorer - Made high quality interaction matrix (12511 rows * 497 columns)
2018-01-19 00:38:10.917 [main] INFO  org.monarchinitiative.exomiser.core.prioritisers.HiPhivePriority - Prioritising genes...
2018-01-19 00:38:46.049 [main] INFO  org.monarchinitiative.exomiser.core.analysis.AbstractAnalysisRunner - Scoring genes
2018-01-19 00:38:46.079 [main] INFO  org.monarchinitiative.exomiser.core.analysis.AbstractAnalysisRunner - Analysed 450 genes containing 683 filtered variants
2018-01-19 00:38:46.079 [main] INFO  org.monarchinitiative.exomiser.core.analysis.AbstractAnalysisRunner - Creating analysis results from VCF and PED files: examples/Pfeiffer.vcf, null
2018-01-19 00:38:46.081 [main] INFO  org.monarchinitiative.exomiser.core.analysis.AbstractAnalysisRunner - Finished analysis in 2m 25s 618ms (145618 ms)
2018-01-19 00:38:46.081 [main] INFO  org.monarchinitiative.exomiser.cli.ExomiserCommandLineRunner - Writing results
2018-01-19 00:38:46.112 [main] INFO  org.monarchinitiative.exomiser.core.writers.HtmlResultsWriter - Writing HTML results
2018-01-19 00:38:46.619 [main] INFO  org.monarchinitiative.exomiser.core.writers.ResultsWriterUtils - 450 of 450 genes passed filters
2018-01-19 00:38:46.620 [main] INFO  org.monarchinitiative.exomiser.core.writers.ResultsWriterUtils - Maximum gene limit set to 0 - Returning all 450 genes which have passed filtering.
2018-01-19 00:38:49.153 [main] ERROR org.thymeleaf.TemplateEngine - [THYMELEAF][main] Exception processing template "results": Error during creation of output
2018-01-19 00:38:49.157 [main] INFO  org.springframework.boot.autoconfigure.logging.AutoConfigurationReportLoggingInitializer - 

Error starting ApplicationContext. To display the auto-configuration report re-run your application with 'debug' enabled.
2018-01-19 00:38:49.164 [main] ERROR org.springframework.boot.SpringApplication - Application startup failed
java.lang.IllegalStateException: Failed to execute CommandLineRunner
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:735)
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:716)
	at org.springframework.boot.SpringApplication.afterRefresh(SpringApplication.java:703)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:304)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1118)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1107)
	at org.monarchinitiative.exomiser.cli.Main.main(Main.java:44)
Caused by: org.thymeleaf.exceptions.TemplateOutputException: Error during creation of output
	at org.thymeleaf.TemplateEngine.process(TemplateEngine.java:1177)
	at org.thymeleaf.TemplateEngine.process(TemplateEngine.java:1060)
	at org.thymeleaf.TemplateEngine.process(TemplateEngine.java:1011)
	at org.thymeleaf.TemplateEngine.process(TemplateEngine.java:955)
	at org.monarchinitiative.exomiser.core.writers.HtmlResultsWriter.writeFile(HtmlResultsWriter.java:75)
	at org.monarchinitiative.exomiser.cli.ExomiserCommandLineRunner.writeResults(ExomiserCommandLineRunner.java:156)
	at org.monarchinitiative.exomiser.cli.ExomiserCommandLineRunner.runAnalysisAndWriteResults(ExomiserCommandLineRunner.java:149)
	at org.monarchinitiative.exomiser.cli.ExomiserCommandLineRunner.runAnalysisFromScript(ExomiserCommandLineRunner.java:137)
	at org.monarchinitiative.exomiser.cli.ExomiserCommandLineRunner.runAnalyses(ExomiserCommandLineRunner.java:83)
	at org.monarchinitiative.exomiser.cli.ExomiserCommandLineRunner.run(ExomiserCommandLineRunner.java:77)
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:732)
	... 6 common frames omitted
	Suppressed: java.nio.charset.UnmappableCharacterException: Input length = 1
		at java.nio.charset.CoderResult.throwException(CoderResult.java:282)
		at sun.nio.cs.StreamEncoder.implWrite(StreamEncoder.java:285)
		at sun.nio.cs.StreamEncoder.write(StreamEncoder.java:125)
		at java.io.OutputStreamWriter.write(OutputStreamWriter.java:207)
		at java.io.BufferedWriter.flushBuffer(BufferedWriter.java:129)
		at java.io.BufferedWriter.close(BufferedWriter.java:265)
		at org.monarchinitiative.exomiser.core.writers.HtmlResultsWriter.writeFile(HtmlResultsWriter.java:76)
		... 12 common frames omitted
Caused by: java.nio.charset.UnmappableCharacterException: Input length = 1
	at java.nio.charset.CoderResult.throwException(CoderResult.java:282)
	at sun.nio.cs.StreamEncoder.implWrite(StreamEncoder.java:285)
	at sun.nio.cs.StreamEncoder.write(StreamEncoder.java:125)
	at java.io.OutputStreamWriter.write(OutputStreamWriter.java:207)
	at java.io.BufferedWriter.flushBuffer(BufferedWriter.java:129)
	at java.io.BufferedWriter.write(BufferedWriter.java:230)
	at java.io.Writer.write(Writer.java:157)
	at org.thymeleaf.templatewriter.AbstractGeneralTemplateWriter.writeText(AbstractGeneralTemplateWriter.java:326)
	at org.thymeleaf.templatewriter.AbstractGeneralTemplateWriter.writeNode(AbstractGeneralTemplateWriter.java:149)
	at org.thymeleaf.templatewriter.AbstractGeneralTemplateWriter.writeElement(AbstractGeneralTemplateWriter.java:257)
	at org.thymeleaf.templatewriter.AbstractGeneralTemplateWriter.writeNode(AbstractGeneralTemplateWriter.java:145)
	at org.thymeleaf.templatewriter.AbstractGeneralTemplateWriter.writeElement(AbstractGeneralTemplateWriter.java:257)
	at org.thymeleaf.templatewriter.AbstractGeneralTemplateWriter.writeNode(AbstractGeneralTemplateWriter.java:145)
	at org.thymeleaf.templatewriter.AbstractGeneralTemplateWriter.writeElement(AbstractGeneralTemplateWriter.java:257)
	at org.thymeleaf.templatewriter.AbstractGeneralTemplateWriter.writeNode(AbstractGeneralTemplateWriter.java:145)
	at org.thymeleaf.templatewriter.AbstractGeneralTemplateWriter.writeDocument(AbstractGeneralTemplateWriter.java:97)
	at org.thymeleaf.templatewriter.AbstractGeneralTemplateWriter.write(AbstractGeneralTemplateWriter.java:72)
	at org.thymeleaf.TemplateEngine.process(TemplateEngine.java:1175)
	... 16 common frames omitted
2018-01-19 00:38:49.165 [main] INFO  org.springframework.context.annotation.AnnotationConfigApplicationContext - Closing org.springframework.context.annotation.AnnotationConfigApplicationContext@1b84f475: startup date [Fri Jan 19 00:35:59 GMT 2018]; root of context hierarchy
2018-01-19 00:38:49.167 [main] INFO  org.springframework.jmx.export.annotation.AnnotationMBeanExporter - Unregistering JMX-exposed beans on shutdown
2018-01-19 00:38:49.167 [main] INFO  org.springframework.jmx.export.annotation.AnnotationMBeanExporter - Unregistering JMX-exposed beans
2018-01-19 00:38:49.168 [main] INFO  com.zaxxer.hikari.pool.HikariPool - exomiser-phenotype-1711 - Close initiated...
2018-01-19 00:38:49.172 [main] INFO  com.zaxxer.hikari.pool.HikariPool - exomiser-phenotype-1711 - Closed.
**

**Comment by kkshaxqd** [comment]
the exomiser-cli-9.0.0.jar also have the same problem when product the HTML.

**Comment by julesjacobsen** [comment]
Can you try running that sample again but use this startup invocation:

```java -Dfile.encoding=UTF-8 -jar exomiser-cli-9.0.1.jar --analysis path/to/your/analysis.yml``` 
or
 ```java -D"file.encoding=UTF-8" -jar exomiser-cli-9.0.1.jar --analysis path/to/your/analysis.yml```
 
if you're using windows. There is likely some character which the HTML writer can't handle from your system native encoding. If that doesn't work you could try switching your system locale to UK and trying again.

**Comment by damiansm** [comment]
I think I have seen this issue when running it from our farm on Genomics
England. I put it down to some oddity in our setup such as a missing
library but maybe it is something more generic?

**Comment by julesjacobsen** [comment]
No, it's a much more fundamental issue with the platform character encoding than a missing library. If this fixes the issue I should be able to put in a change so people won't need to use the `-Dfile.encoding=UTF-8`  command.

**Comment by kkshaxqd** [comment]
Thanks, It's work,  the HTML can product  normal,  It's great,  the reason is just this!!! Very thanks.

**Comment by julesjacobsen** [comment]
Fixed in release 10.0.0
