### ISSUE TITLE
Exomiser fails for unusual value in VCF sample column

### ISSUE THREAD

**Issue by estyholt** [exomiser/Exomiser#257]
Hello,

Just wanted you to be aware of an issue we've encountered while running Exomiser (v10.0.0):
Some of our VCF files contained GL value = "-inf",
For example (part of the line):
MT         16568    .               T              TG              GT:GL:GQ:NR    1/1:-inf,-10.36,-9.67:27:1

We had to amend those lines in order to get Exomiser run successfully. 
Attached is the ERROR log.
[Exomiser.10.log](https://github.com/exomiser/Exomiser/files/1837857/Exomiser.10.log)

Thank you

**Comment by julesjacobsen** [comment]
Thanks for the feedback - this is an issue with the underlying HTSJDK library/your VCF file:

```java
Caused by: java.lang.NumberFormatException: For input string: "-inf"
        at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2043)
        at sun.misc.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
        at java.lang.Double.parseDouble(Double.java:538)
        at htsjdk.variant.variantcontext.GenotypeLikelihoods.parseDeprecatedGLString(GenotypeLikelihoods.java:264)
```

```-inf``` is not a valid floating point (e.g. 0.001) value which causes the exception.
