### ISSUE TITLE
NumberFormatException when writing results to vcf

### ISSUE THREAD

**Issue by kshefchek** [exomiser/Exomiser#259]
I am getting a NumberFormatException during the output phase of exomiser:

    Caused by: java.lang.NumberFormatException: For input string: "2187581795"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:583)
	at java.lang.Integer.valueOf(Integer.java:766)
	at htsjdk.variant.vcf.VCFContigHeaderLine.getSAMSequenceRecord(VCFContigHeaderLine.java:81)
	at htsjdk.variant.vcf.VCFHeader.getSequenceDictionary(VCFHeader.java:206)
	at de.charite.compbio.jannovar.htsjdk.VariantContextWriterConstructionHelper.makeBuilder(VariantContextWriterConstructionHelper.java:107)
	at de.charite.compbio.jannovar.htsjdk.VariantContextWriterConstructionHelper.openVariantContextWriter(VariantContextWriterConstructionHelper.java:87)
	at org.monarchinitiative.exomiser.core.writers.VcfResultsWriter.writeFile(VcfResultsWriter.java:119)
	at org.monarchinitiative.exomiser.core.writers.AnalysisResultsWriter.writeForInheritanceMode(AnalysisResultsWriter.java:69)
	at org.monarchinitiative.exomiser.core.writers.AnalysisResultsWriter.writeToFile(AnalysisResultsWriter.java:60)

Is this likely an issue with the vcf? If so I can mock up an example without real data.

**Comment by martenj** [comment]
Hi Kent,

this is most likely a problem with the VCF or to be precise the number "2187581795". It's simply to high. HTSJDK is trying to parse an Integer `java.lang.Integer.parseInt(Integer.java:583, but  the max Value for that is 2147483647.

Best.
Marten

**Comment by kshefchek** [comment]
Taking a closer look, the vcf is reporting chromosome 12 has a length of 2.1 billion base pairs?!  I'm not familiar with how the file was generated, but I can remove the config lengths and rerun.

**Comment by pnrobinson** [comment]
@kshefchek -- this most likely indicates that your VCF file is buggy, but can you post the offending line and the context? Are there valid contigs of this length (not for any of the species currently supported by Jannovar)

**Comment by kshefchek** [comment]
sure:

    ##contig=<ID=12,length=2187581795>

This is a human merged trio (exome), so obviously an error
