### ISSUE TITLE
Exomiser - WGS trio - thread starvation or clock leap

### ISSUE THREAD

**Issue by stanedav** [exomiser/Exomiser#286]
Hello,

I am trying to run exomiser for my WGS trio - I have prepared vcf with three samples (GATK pipeline with gvcf called into one vcf. Then I am using Exomiser 10.1.0 with setup provided in attached files. 

I made a test on linux machine with 32 GB ram and on windows machine with 32 GB ram, both with same error, any PC went into sleep mode.

Please, could you help me with this error?

```
Error output in command line:
`2018-09-19 13:58:14.364 [main] INFO  org.monarchinitiative.exomiser.core.analysis.AbstractAnalysisRunner - Loaded 5900000 variants - 145963 passed variant filters...
2018-09-19 13:58:36.684 [main] INFO  org.monarchinitiative.exomiser.core.analysis.AbstractAnalysisRunner - Loaded 6000000 variants - 147915 passed variant filters...
2018-09-19 13:59:00.859 [main] INFO  org.monarchinitiative.exomiser.core.analysis.AbstractAnalysisRunner - Loaded 6100000 variants - 150070 passed variant filters...
2018-09-19 13:59:40.300 [main] INFO  org.monarchinitiative.exomiser.core.analysis.AbstractAnalysisRunner - Loaded 6200000 variants - 153632 passed variant filters...
2018-09-19 14:00:05.860 [main] INFO  org.monarchinitiative.exomiser.core.analysis.AbstractAnalysisRunner - Loaded 6300000 variants - 155776 passed variant filters...
2018-09-19 14:00:21.110 [main] INFO  org.monarchinitiative.exomiser.core.analysis.AbstractAnalysisRunner - Loaded 6400000 variants - 157093 passed variant filters...
2018-09-19 14:00:21.811 [main] INFO  org.monarchinitiative.exomiser.core.genome.VariantFactoryImpl - Processed 6310783 variant records into 6389070 single allele variants, 100083 are missing annotations, most likely due to non-numeric chromosome designations
2018-09-19 14:00:21.811 [main] INFO  org.monarchinitiative.exomiser.core.genome.VariantFactoryImpl - Variant annotation finished in 30m 2s 424ms (1802424 ms)
2018-09-19 14:00:21.811 [main] INFO  org.monarchinitiative.exomiser.core.analysis.AbstractAnalysisRunner - Loaded 6489153 variants - 157093 passed variant filters
2018-09-19 14:00:21.871 [main] INFO  org.monarchinitiative.exomiser.core.analysis.AbstractAnalysisRunner - Checking inheritance mode compatibility with [AUTOSOMAL_DOMINANT, AUTOSOMAL_RECESSIVE, X_RECESSIVE, X_DOMINANT, MITOCHONDRIAL] for genes which passed filters
2018-09-19 14:00:55.607 [main] INFO  org.monarchinitiative.exomiser.core.analysis.util.InheritanceModeAnalyser - Warning - this will take a while. Testing gene KMT2C with 1693 passed variants for inheritance mode compatibility!
2018-09-19 14:03:18.304 [exomiser-phenotype-1807 housekeeper] WARN  com.zaxxer.hikari.pool.HikariPool - exomiser-phenotype-1807 - Thread starvation or clock leap detected (housekeeper delta=1m52s716ms830µs249ns).
2018-09-19 14:03:18.304 [exomiser-genome-hg19-1805 housekeeper] WARN  com.zaxxer.hikari.pool.HikariPool - exomiser-genome-hg19-1805 - Thread starvation or clock leap detected (housekeeper delta=1m44s927ms588µs999ns).
2018-09-19 14:09:42.635 [main] INFO  org.monarchinitiative.exomiser.core.analysis.util.InheritanceModeAnalyser - Warning - this will take a while. Testing gene NBPF9 with 5927 passed variants for inheritance mode compatibility!
2018-09-19 14:14:52.234 [exomiser-genome-hg19-1805 housekeeper] WARN  com.zaxxer.hikari.pool.HikariPool - exomiser-genome-hg19-1805 - Thread starvation or clock leap detected (housekeeper delta=3m32s902ms929µs150ns).
2018-09-19 14:14:52.234 [exomiser-phenotype-1807 housekeeper] WARN  com.zaxxer.hikari.pool.HikariPool - exomiser-phenotype-1807 - Thread starvation or clock leap detected (housekeeper delta=3m32s902ms852µs537ns).
2018-09-19 14:20:06.404 [exomiser-genome-hg19-1805 housekeeper] WARN  com.zaxxer.hikari.pool.HikariPool - exomiser-genome-hg19-1805 - Thread starvation or clock leap detected (housekeeper delta=4m12s402ms195µs420ns).
2018-09-19 14:20:06.404 [exomiser-phenotype-1807 housekeeper] WARN  com.zaxxer.hikari.pool.HikariPool - exomiser-phenotype-1807 - Thread starvation or clock leap detected (housekeeper delta=4m12s402ms195µs290ns).
2018-09-19 14:24:25.539 [exomiser-phenotype-1807 housekeeper] WARN  com.zaxxer.hikari.pool.HikariPool - exomiser-phenotype-1807 - Thread starvation or clock leap detected (housekeeper delta=4m19s134ms634µs493ns).
2018-09-19 14:24:25.539 [exomiser-genome-hg19-1805 housekeeper] WARN  com.zaxxer.hikari.pool.HikariPool - exomiser-genome-hg19-1805 - Thread starvation or clock leap detected (housekeeper delta=4m19s134ms640µs124ns).
2018-09-19 14:28:42.210 [exomiser-phenotype-1807 housekeeper] WARN  com.zaxxer.hikari.pool.HikariPool - exomiser-phenotype-1807 - Thread starvation or clock leap detected (housekeeper delta=4m16s668ms174µs731ns).
2018-09-19 14:28:42.210 [exomiser-genome-hg19-1805 housekeeper] WARN  com.zaxxer.hikari.pool.HikariPool - exomiser-genome-hg19-1805 - Thread starvation or clock leap detected (housekeeper delta=4m16s668ms169µs40ns).
2018-09-19 14:33:06.487 [exomiser-genome-hg19-1805 housekeeper] WARN  com.zaxxer.hikari.pool.HikariPool - exomiser-genome-hg19-1805 - Thread starvation or clock leap detected (housekeeper delta=4m24s277ms286µs65ns).
2018-09-19 14:33:06.487 [exomiser-phenotype-1807 housekeeper] WARN  com.zaxxer.hikari.pool.HikariPool - exomiser-phenotype-1807 - Thread starvation or clock leap detected (housekeeper delta=4m24s279ms478µs546ns).
2018-09-19 14:37:39.349 [exomiser-genome-hg19-1805 housekeeper] WARN  com.zaxxer.hikari.pool.HikariPool - exomiser-genome-hg19-1805 - Thread starvation or clock leap detected (housekeeper delta=4m32s864ms132µs124ns).
2018-09-19 14:37:39.349 [exomiser-phenotype-1807 housekeeper] WARN  com.zaxxer.hikari.pool.HikariPool - exomiser-phenotype-1807 - Thread starvation or clock leap detected (housekeeper delta=4m32s861ms947µs237ns).
2018-09-19 14:43:07.300 [exomiser-genome-hg19-1805 housekeeper] WARN  com.zaxxer.hikari.pool.HikariPool - exomiser-genome-hg19-1805 - Thread starvation or clock leap detected (housekeeper delta=5m27s950ms950µs350ns).
2018-09-19 14:43:07.303 [exomiser-phenotype-1807 housekeeper] WARN  com.zaxxer.hikari.pool.HikariPool - exomiser-phenotype-1807 - Thread starvation or clock leap detected (housekeeper delta=5m27s954ms460µs12ns).
2018-09-19 14:47:54.988 [exomiser-genome-hg19-1805 housekeeper] WARN  com.zaxxer.hikari.pool.HikariPool - exomiser-genome-hg19-1805 - Thread starvation or clock leap detected (housekeeper delta=4m47s688ms63µs791ns).
2018-09-19 14:47:54.989 [exomiser-phenotype-1807 housekeeper] WARN  com.zaxxer.hikari.pool.HikariPool - exomiser-phenotype-1807 - Thread starvation or clock leap detected (housekeeper delta=4m47s684ms546µs645ns).
2018-09-19 14:52:48.784 [exomiser-genome-hg19-1805 housekeeper] WARN  com.zaxxer.hikari.pool.HikariPool - exomiser-genome-hg19-1805 - Thread starvation or clock leap detected (housekeeper delta=4m53s796ms478µs619ns).
2018-09-19 14:52:48.784 [exomiser-phenotype-1807 housekeeper] WARN  com.zaxxer.hikari.pool.HikariPool - exomiser-phenotype-1807 - Thread starvation or clock leap detected (housekeeper delta=4m53s796ms478µs609ns).
2018-09-19 14:57:47.297 [exomiser-phenotype-1807 housekeeper] WARN  com.zaxxer.hikari.pool.HikariPool - exomiser-phenotype-1807 - Thread starvation or clock leap detected (housekeeper delta=4m58s510ms439µs162ns).
2018-09-19 14:57:47.297 [exomiser-genome-hg19-1805 housekeeper] WARN  com.zaxxer.hikari.pool.HikariPool - exomiser-genome-hg19-1805 - Thread starvation or clock leap detected (housekeeper delta=4m58s510ms439µs232ns).
2018-09-19 15:02:57.785 [exomiser-phenotype-1807 housekeeper] WARN  com.zaxxer.hikari.pool.HikariPool - exomiser-phenotype-1807 - Thread starvation or clock leap detected (housekeeper delta=5m10s489ms987µs280ns).
2018-09-19 15:02:57.785 [exomiser-genome-hg19-1805 housekeeper] WARN  com.zaxxer.hikari.pool.HikariPool - exomiser-genome-hg19-1805 - Thread starvation or clock leap detected (housekeeper delta=5m10s489ms987µs280ns).
2018-09-19 15:08:06.540 [exomiser-phenotype-1807 housekeeper] WARN  com.zaxxer.hikari.pool.HikariPool - exomiser-phenotype-1807 - Thread starvation or clock leap detected (housekeeper delta=5m8s755ms75µs144ns).
2018-09-19 15:08:06.540 [exomiser-genome-hg19-1805 housekeeper] WARN  com.zaxxer.hikari.pool.HikariPool - exomiser-genome-hg19-1805 - Thread starvation or clock leap detected (housekeeper delta=5m8s755ms75µs64ns).
2018-09-19 15:13:40.465 [exomiser-phenotype-1807 housekeeper] WARN  com.zaxxer.hikari.pool.HikariPool - exomiser-phenotype-1807 - Thread starvation or clock leap detected (housekeeper delta=5m33s925ms749µs959ns).
2018-09-19 15:13:40.465 [exomiser-genome-hg19-1805 housekeeper] WARN  com.zaxxer.hikari.pool.HikariPool - exomiser-genome-hg19-1805 - Thread starvation or clock leap detected (housekeeper delta=5m33s925ms750µs39ns).
2018-09-19 15:18:56.481 [exomiser-phenotype-1807 housekeeper] WARN  com.zaxxer.hikari.pool.HikariPool - exomiser-phenotype-1807 - Thread starvation or clock leap detected (housekeeper delta=5m16s15ms355µs987ns).
2018-09-19 15:18:56.481 [exomiser-genome-hg19-1805 housekeeper] WARN  com.zaxxer.hikari.pool.HikariPool - exomiser-genome-hg19-1805 - Thread starvation or clock leap detected (housekeeper delta=5m16s15ms355µs917ns).
2018-09-19 15:24:13.625 [exomiser-genome-hg19-1805 housekeeper] WARN  com.zaxxer.hikari.pool.HikariPool - exomiser-genome-hg19-1805 - Thread starvation or clock leap detected (housekeeper delta=5m17s144ms367µs293ns).
2018-09-19 15:24:13.625 [exomiser-phenotype-1807 housekeeper] WARN  com.zaxxer.hikari.pool.HikariPool - exomiser-phenotype-1807 - Thread starvation or clock leap detected (housekeeper delta=5m17s144ms367µs453ns).
2018-09-19 15:29:51.536 [exomiser-phenotype-1807 housekeeper] WARN  com.zaxxer.hikari.pool.HikariPool - exomiser-phenotype-1807 - Thread starvation or clock leap detected (housekeeper delta=5m37s910ms613µs781ns).
2018-09-19 15:29:51.536 [exomiser-genome-hg19-1805 housekeeper] WARN  com.zaxxer.hikari.pool.HikariPool - exomiser-genome-hg19-1805 - Thread starvation or clock leap detected (housekeeper delta=5m37s910ms629µs170ns).
2018-09-19 15:36:57.590 [exomiser-genome-hg19-1805 housekeeper] WARN  com.zaxxer.hikari.pool.HikariPool - exomiser-genome-hg19-1805 - Thread starvation or clock leap detected (housekeeper delta=7m6s53ms742µs413ns).
2018-09-19 15:36:57.590 [exomiser-phenotype-1807 housekeeper] WARN  com.zaxxer.hikari.pool.HikariPool - exomiser-phenotype-1807 - Thread starvation or clock leap detected (housekeeper delta=7m6s53ms929µs935ns).
2018-09-19 15:48:46.101 [exomiser-phenotype-1807 housekeeper] WARN  com.zaxxer.hikari.pool.HikariPool - exomiser-phenotype-1807 - Thread starvation or clock leap detected (housekeeper delta=11m48s511ms721µs495ns).
2018-09-19 15:48:46.103 [exomiser-genome-hg19-1805 housekeeper] WARN  com.zaxxer.hikari.pool.HikariPool - exomiser-genome-hg19-1805 - Thread starvation or clock leap detected (housekeeper delta=11m48s513ms66µs367ns).
2018-09-19 15:48:46.273 [main] INFO  org.springframework.boot.autoconfigure.logging.AutoConfigurationReportLoggingInitializer - 

Error starting ApplicationContext. To display the auto-configuration report re-run your application with 'debug' enabled.
2018-09-19 15:48:46.360 [main] ERROR org.springframework.boot.SpringApplication - Application startup failed
java.lang.OutOfMemoryError: Java heap space
	at java.util.Arrays.copyOf(Arrays.java:3181)
	at java.util.ArrayList.grow(ArrayList.java:265)
	at java.util.ArrayList.ensureExplicitCapacity(ArrayList.java:239)
	at java.util.ArrayList.ensureCapacityInternal(ArrayList.java:231)
	at java.util.ArrayList.add(ArrayList.java:462)
	at de.charite.compbio.jannovar.mendel.impl.MendelianCheckerARCompoundHet.collectTroCandidatesWithParents(MendelianCheckerARCompoundHet.java:218)
	at de.charite.compbio.jannovar.mendel.impl.MendelianCheckerARCompoundHet.collectTrioCandidates(MendelianCheckerARCompoundHet.java:156)
	at de.charite.compbio.jannovar.mendel.impl.MendelianCheckerARCompoundHet.filterCompatibleRecordsMultiSample(MendelianCheckerARCompoundHet.java:80)
	at de.charite.compbio.jannovar.mendel.impl.MendelianCheckerARCompoundHet.filterCompatibleRecords(MendelianCheckerARCompoundHet.java:58)
	at de.charite.compbio.jannovar.mendel.MendelianInheritanceChecker.filterCompatibleRecords(MendelianInheritanceChecker.java:150)
	at de.charite.compbio.jannovar.mendel.MendelianInheritanceChecker.checkMendelianInheritance(MendelianInheritanceChecker.java:73)
	at de.charite.compbio.jannovar.mendel.MendelianInheritanceChecker.checkMendelianInheritance(MendelianInheritanceChecker.java:84)
	at org.monarchinitiative.exomiser.core.analysis.util.InheritanceModeAnnotator.computeCompatibleInheritanceModes(InheritanceModeAnnotator.java:84)
	at org.monarchinitiative.exomiser.core.analysis.util.InheritanceModeAnalyser.checkInheritanceCompatibilityOfPassedVariants(InheritanceModeAnalyser.java:100)
	at org.monarchinitiative.exomiser.core.analysis.util.InheritanceModeAnalyser.lambda$analyseInheritanceModes$0(InheritanceModeAnalyser.java:86)
	at org.monarchinitiative.exomiser.core.analysis.util.InheritanceModeAnalyser$$Lambda$163/630537190.accept(Unknown Source)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.monarchinitiative.exomiser.core.analysis.util.InheritanceModeAnalyser.analyseInheritanceModes(InheritanceModeAnalyser.java:66)
	at org.monarchinitiative.exomiser.core.analysis.AbstractAnalysisRunner.analyseGeneCompatibilityWithInheritanceMode(AbstractAnalysisRunner.java:295)
	at org.monarchinitiative.exomiser.core.analysis.AbstractAnalysisRunner.runSteps(AbstractAnalysisRunner.java:285)
	at org.monarchinitiative.exomiser.core.analysis.AbstractAnalysisRunner.run(AbstractAnalysisRunner.java:114)
	at org.monarchinitiative.exomiser.core.Exomiser.run(Exomiser.java:64)
	at org.monarchinitiative.exomiser.cli.ExomiserCommandLineRunner.runAnalysisAndWriteResults(ExomiserCommandLineRunner.java:118)
	at org.monarchinitiative.exomiser.cli.ExomiserCommandLineRunner.runAnalysisFromScript(ExomiserCommandLineRunner.java:114)
	at org.monarchinitiative.exomiser.cli.ExomiserCommandLineRunner.runAnalyses(ExomiserCommandLineRunner.java:77)
	at org.monarchinitiative.exomiser.cli.ExomiserCommandLineRunner.run(ExomiserCommandLineRunner.java:
```
[yml_and_properties_files.zip](https://github.com/exomiser/Exomiser/files/2437157/yml_and_properties_files.zip)

`

**Comment by julesjacobsen** [comment]
You need to supply a PED file in order that the trio can be properly filtered. You also have the  hiPhiveprioritiser listed twice - remove this one:  ```hiPhivePrioritiser: {runParams: 'human'},```

what were your command-line arguments to launch it? I would recommend something like ```java -jar -Xms100m -Xmx10g```
