### ISSUE TITLE
Build error (develop). Unsatisfied dependency

### ISSUE THREAD

**Issue by pnrobinson** [exomiser/Exomiser#317]
```
[ERROR] testGenomeAnalysisServiceProviderIsAutoConfigured  Time elapsed: 0.716 s  <<< ERROR!
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'analysisFactory' defined in URL [jar:file:/home/peter/IdeaProjects/Exomiser/exomiser-core/target/exomiser-core-12.0.0-SNAPSHOT.jar!/org/monarchinitiative/exomiser/core/analysis/AnalysisFactory.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'genomeAnalysisServiceProvider' defined in class path resource [org/monarchinitiative/exomiser/autoconfigure/genome/GenomeAnalysisServiceAutoConfiguration.class]: Unsatisfied dependency expressed through method 'genomeAnalysisServiceProvider' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.monarchinitiative.exomiser.autoconfigure.genome.Hg19GenomeAnalysisServiceAutoConfiguration': Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.monarchinitiative.exomiser.autoconfigure.genome.Hg19GenomeAnalysisServiceAutoConfiguration$$EnhancerBySpringCGLIB$$f3c48f4a]: Constructor threw exception; nested exception is java.lang.IllegalStateException: The file is locked: nio:/home/peter/IdeaProjects/Exomiser/exomiser-spring-boot-autoconfigure/src/test/resources/data/1710_hg19/1710_hg19_variants.mv.db [1.4.197/7]
	at org.monarchinitiative.exomiser.autoconfigure.ExomiserAutoConfigurationTest.testGenomeAnalysisServiceProviderIsAutoConfigured(ExomiserAutoConfigurationTest.java:52)
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'genomeAnalysisServiceProvider' defined in class path resource [org/monarchinitiative/exomiser/autoconfigure/genome/GenomeAnalysisServiceAutoConfiguration.class]: Unsatisfied dependency expressed through method 'genomeAnalysisServiceProvider' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.monarchinitiative.exomiser.autoconfigure.genome.Hg19GenomeAnalysisServiceAutoConfiguration': Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.monarchinitiative.exomiser.autoconfigure.genome.Hg19GenomeAnalysisServiceAutoConfiguration$$EnhancerBySpringCGLIB$$f3c48f4a]: Constructor threw exception; nested exception is java.lang.IllegalStateException: The file is locked: nio:/home/peter/IdeaProjects/Exomiser/exomiser-spring-boot-autoconfigure/src/test/resources/data/1710_hg19/1710_hg19_variants.mv.db [1.4.197/7]
	at org.monarchinitiative.exomiser.autoconfigure.ExomiserAutoConfigurationTest.testGenomeAnalysisServiceProviderIsAutoConfigured(ExomiserAutoConfigurationTest.java:52)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.monarchinitiative.exomiser.autoconfigure.genome.Hg19GenomeAnalysisServiceAutoConfiguration': Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.monarchinitiative.exomiser.autoconfigure.genome.Hg19GenomeAnalysisServiceAutoConfiguration$$EnhancerBySpringCGLIB$$f3c48f4a]: Constructor threw exception; nested exception is java.lang.IllegalStateException: The file is locked: nio:/home/peter/IdeaProjects/Exomiser/exomiser-spring-boot-autoconfigure/src/test/resources/data/1710_hg19/1710_hg19_variants.mv.db [1.4.197/7]
	at org.monarchinitiative.exomiser.autoconfigure.ExomiserAutoConfigurationTest.testGenomeAnalysisServiceProviderIsAutoConfigured(ExomiserAutoConfigurationTest.java:52)
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.monarchinitiative.exomiser.autoconfigure.genome.Hg19GenomeAnalysisServiceAutoConfiguration$$EnhancerBySpringCGLIB$$f3c48f4a]: Constructor threw exception; nested exception is java.lang.IllegalStateException: The file is locked: nio:/home/peter/IdeaProjects/Exomiser/exomiser-spring-boot-autoconfigure/src/test/resources/data/1710_hg19/1710_hg19_variants.mv.db [1.4.197/7]
	at org.monarchinitiative.exomiser.autoconfigure.ExomiserAutoConfigurationTest.testGenomeAnalysisServiceProviderIsAutoConfigured(ExomiserAutoConfigurationTest.java:52)
Caused by: java.lang.IllegalStateException: The file is locked: nio:/home/peter/IdeaProjects/Exomiser/exomiser-spring-boot-autoconfigure/src/test/resources/data/1710_hg19/1710_hg19_variants.mv.db [1.4.197/7]
	at org.monarchinitiative.exomiser.autoconfigure.ExomiserAutoConfigurationTest.testGenomeAnalysisServiceProviderIsAutoConfigured(ExomiserAutoConfigurationTest.java:52)
Caused by: java.nio.channels.OverlappingFileLockException
	at org.monarchinitiative.exomiser.autoconfigure.ExomiserAutoConfigurationTest.testGenomeAnalysisServiceProviderIsAutoConfigured(ExomiserAutoConfigurationTest.java:52)
``

**Comment by julesjacobsen** [comment]
Hi Peter, this is caused by:

```
Caused by: java.lang.IllegalStateException: The file is locked: nio:/home/peter/IdeaProjects/Exomiser/exomiser-spring-boot-autoconfigure/src/test/resources/data/1710_hg19/1710_hg19_variants.mv.db [1.4.197/7]
```
i.e. the ```1710_hg19_variants.mv.db``` file was being accessed twice by the same JVM. This happens irregularly during the CI builds too, but never on my local machine. Will see what I can do.
