### ISSUE TITLE
Exomiser crash

### ISSUE THREAD

**Issue by pnrobinson** [exomiser/Exomiser#323]
Using the latest develop version (12-SNAPSHOT)
The logger shows that we get this while we are parsing a VCF file
and get to this variant: 1:866511C>CCCCT
```
java.lang.NoSuchMethodError: de.charite.compbio.jannovar.annotation.Annotation.getEffects()Lcom/google/common/collect/ImmutableSortedSet;
	at org.monarchinitiative.exomiser.core.genome.JannovarVariantAnnotator.getDistFromNearestGene(JannovarVariantAnnotator.java:165)
	at org.monarchinitiative.exomiser.core.genome.JannovarVariantAnnotator.toTranscriptAnnotation(JannovarVariantAnnotator.java:146)
	at org.monarchinitiative.exomiser.core.genome.JannovarVariantAnnotator.buildTranscriptAnnotations(JannovarVariantAnnotator.java:133)
	at org.monarchinitiative.exomiser.core.genome.JannovarVariantAnnotator.buildVariantAlleleAnnotation(JannovarVariantAnnotator.java:109)
	at org.monarchinitiative.exomiser.core.genome.JannovarVariantAnnotator.annotate(JannovarVariantAnnotator.java:95)
(... other stuff from calling code)
```

**Comment by pnrobinson** [comment]
This was an issue on my end, all is fine now, thanks!
