### ISSUE TITLE
Error: Contig chr1 does not have a length field.

### ISSUE THREAD

**Issue by bsmith030465** [exomiser/Exomiser#384]
Hi,

I was trying to run exomiser on a sample, but get an error:

`
.
.
2020-09-30 10:09:47.973  INFO 5772 --- [           main] o.m.e.core.genome.VariantFactoryImpl     : Processed 6604493 variant records into 1818288 single allele variants, 7252 are missing annotations, most likely due to non-numeric chromosome designations
2020-09-30 10:09:47.973  INFO 5772 --- [           main] o.m.e.core.genome.VariantFactoryImpl     : Variant annotation finished in 15m 31s 935ms (931935 ms)
2020-09-30 10:09:47.974  INFO 5772 --- [           main] o.m.e.c.analysis.AbstractAnalysisRunner  : Loaded 1825540 variants - 1595 passed variant filters
2020-09-30 10:09:47.998  INFO 5772 --- [           main] o.m.e.c.analysis.AbstractAnalysisRunner  : Checking inheritance mode compatibility with [AUTOSOMAL_DOMINANT, AUTOSOMAL_RECESSIVE, X_RECESSIVE, X_DOMINANT, MITOCHONDRIAL] for genes which passed filters
2020-09-30 10:09:48.500  INFO 5772 --- [           main] o.m.e.c.analysis.AbstractAnalysisRunner  : Running GeneFilter: InheritanceFilter{compatibleModes=[AUTOSOMAL_DOMINANT, AUTOSOMAL_RECESSIVE, X_RECESSIVE, X_DOMINANT, MITOCHONDRIAL]}2020-09-30 10:09:48.569  INFO 5772 --- [           main] o.m.e.c.analysis.AbstractAnalysisRunner  : Running Prioritiser: OmimPrioritiser{}
2020-09-30 10:09:51.679  INFO 5772 --- [           main] o.m.e.c.analysis.AbstractAnalysisRunner  : Running Prioritiser: HiPhivePriority{options=HiPhiveOptions{diseaseId='', candidateGeneSymbol='', benchmarkingEnabled=false, runPpi=true, runHuman=true, runMouse=true, runFish=true}}
2020-09-30 10:09:51.685  WARN 5772 --- [           main] o.m.e.c.phenotype.service.HpoIdChecker   : Input HP:0032929 - unable to find current id. Returning input HP:0032929
2020-09-30 10:09:55.373  INFO 5772 --- [           main] o.m.e.c.analysis.AbstractAnalysisRunner  : Scoring genes
2020-09-30 10:09:55.513  INFO 5772 --- [           main] o.m.e.c.analysis.AbstractAnalysisRunner  : Analysed 689 genes containing 1076 filtered variants
2020-09-30 10:09:55.514  INFO 5772 --- [           main] o.m.e.c.analysis.AbstractAnalysisRunner  : Variant filter stats are:
2020-09-30 10:09:55.515  INFO 5772 --- [           main] o.m.e.c.analysis.AbstractAnalysisRunner  : VARIANT_EFFECT_FILTER: pass=26921 fail=1791367
2020-09-30 10:09:55.515  INFO 5772 --- [           main] o.m.e.c.analysis.AbstractAnalysisRunner  : FREQUENCY_FILTER: pass=1595 fail=25326
2020-09-30 10:09:55.515  INFO 5772 --- [           main] o.m.e.c.analysis.AbstractAnalysisRunner  : PATHOGENICITY_FILTER: pass=1595 fail=0
2020-09-30 10:09:55.515  INFO 5772 --- [           main] o.m.e.c.analysis.AbstractAnalysisRunner  : INHERITANCE_FILTER: pass=1076 fail=519
2020-09-30 10:09:55.515  INFO 5772 --- [           main] o.m.e.c.analysis.AbstractAnalysisRunner  : Creating analysis results from VCF /home/pchopra/tyep/vedant/SL158185/TYEP0006.SL158185.merge.filter.sorted.vcf.gz
2020-09-30 10:09:55.516  INFO 5772 --- [           main] o.m.e.c.analysis.AbstractAnalysisRunner  : Finished analysis in 15m 40s 9ms (940009 ms)
2020-09-30 10:09:55.517  INFO 5772 --- [           main] o.m.e.c.writers.AnalysisResultsWriter    : Writing results...
2020-09-30 10:09:57.712 ERROR 5772 --- [           main] o.m.e.cli.ExomiserCommandLineRunner      :

htsjdk.tribble.TribbleException: Contig chr1 does not have a length field.
    at htsjdk.variant.vcf.VCFContigHeaderLine.getSAMSequenceRecord(VCFContigHeaderLine.java:80)
    at htsjdk.variant.vcf.VCFHeader.getSequenceDictionary(VCFHeader.java:206)
    at de.charite.compbio.jannovar.htsjdk.VariantContextWriterConstructionHelper.makeBuilder(VariantContextWriterConstructionHelper.java:97)
    at de.charite.compbio.jannovar.htsjdk.VariantContextWriterConstructionHelper.openVariantContextWriter(VariantContextWriterConstructionHelper.java:77)
    at org.monarchinitiative.exomiser.core.writers.VcfResultsWriter.writeFile(VcfResultsWriter.java:119)
    at org.monarchinitiative.exomiser.core.writers.AnalysisResultsWriter.writeResultsToFileForMoiWithFormat(AnalysisResultsWriter.java:83)
    at org.monarchinitiative.exomiser.core.writers.AnalysisResultsWriter.writeForInheritanceMode(AnalysisResultsWriter.java:77)
    at org.monarchinitiative.exomiser.core.writers.AnalysisResultsWriter.writeToFile(AnalysisResultsWriter.java:70)
    at org.monarchinitiative.exomiser.cli.ExomiserCommandLineRunner.runAnalysisAndWriteResults(ExomiserCommandLineRunner.java:129)
    at org.monarchinitiative.exomiser.cli.ExomiserCommandLineRunner.runAnalysisFromScript(ExomiserCommandLineRunner.java:124)
    at org.monarchinitiative.exomiser.cli.ExomiserCommandLineRunner.runAnalyses(ExomiserCommandLineRunner.java:83)
    at org.monarchinitiative.exomiser.cli.ExomiserCommandLineRunner.run(ExomiserCommandLineRunner.java:74)
    at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:813)
    at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:797)
    at org.springframework.boot.SpringApplication.run(SpringApplication.java:324)
    at org.springframework.boot.SpringApplication.run(SpringApplication.java:1260)
    at org.springframework.boot.SpringApplication.run(SpringApplication.java:1248)
    at org.monarchinitiative.exomiser.cli.Main.main(Main.java:44)

2020-09-30 10:09:57.725  INFO 5772 --- [           main] com.zaxxer.hikari.HikariDataSource       : exomiser-phenotype-2003 - Shutdown initiated...
2020-09-30 10:09:57.734  INFO 5772 --- [           main] com.zaxxer.hikari.HikariDataSource       : exomiser-phenotype-2003 - Shutdown completed.
2020-09-30 10:09:57.734  INFO 5772 --- [           main] org.monarchinitiative.exomiser.cli.Main  : Exomising finished - Bye!`

What do I need to do/check?

thanks!

**Comment by julesjacobsen** [comment]
Is there a chr1 in the VCF header config section? Is it missing a length?

**Comment by julesjacobsen** [comment]
Closing due to lack of response.
