### ISSUE TITLE
CADD error

### ISSUE THREAD

**Issue by shwetanavle** [exomiser/Exomiser#397]
I have downloaded the gnomad.genomes.r3.0.indel.tsv and gnomad.genomes.r3.0.indel.tsv.gz.tbi in my examiner folder and I gave the path in applications.properties as examiner-cli-12.1.0/data/2102_hg38/gnomad.genomes.r3.0.indel.tsv and both files are present in that data folder and I have made changes in iml file also but still I am getting the below error.
Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'exomiserCommandLineRunner': Unsatisfied dependency expressed through field 'analysisParser'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'analysisParser' defined in URL [jar:file:/Users/admin/Desktop/exomiser-cli-12.1.0/lib/exomiser-core-12.1.0.jar!/org/monarchinitiative/exomiser/core/analysis/AnalysisParser.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'genomeAnalysisServiceProvider' defined in class path resource [org/monarchinitiative/exomiser/autoconfigure/genome/GenomeAnalysisServiceAutoConfiguration.class]: Unsatisfied dependency expressed through method 'genomeAnalysisServiceProvider' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.monarchinitiative.exomiser.autoconfigure.genome.Hg38GenomeAnalysisServiceAutoConfiguration': Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.monarchinitiative.exomiser.autoconfigure.genome.Hg38GenomeAnalysisServiceAutoConfiguration$$EnhancerBySpringCGLIB$$408163f2]: Constructor threw exception; nested exception is org.monarchinitiative.exomiser.autoconfigure.ExomiserAutoConfigurationException: Failed to load/find file /Users/admin/Desktop/exomiser-cli-12.1.0/data/2102_hg38/exomiser-cli-12.1.0/data/2102_hg38/gnomad.genomes.r3.0.indel.tsv. Please check exomiser properties file points to a valid tabix .gz file.
2021-04-23 16:06:33.460  INFO 1628 --- [           main] ConditionEvaluationReportLoggingListener : 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2021-04-23 16:06:33.463 ERROR 1628 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'exomiserCommandLineRunner': Unsatisfied dependency expressed through field 'analysisParser'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'analysisParser' defined in URL [jar:file:/Users/admin/Desktop/exomiser-cli-12.1.0/lib/exomiser-core-12.1.0.jar!/org/monarchinitiative/exomiser/core/analysis/AnalysisParser.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'genomeAnalysisServiceProvider' defined in class path resource [org/monarchinitiative/exomiser/autoconfigure/genome/GenomeAnalysisServiceAutoConfiguration.class]: Unsatisfied dependency expressed through method 'genomeAnalysisServiceProvider' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.monarchinitiative.exomiser.autoconfigure.genome.Hg38GenomeAnalysisServiceAutoConfiguration': Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.monarchinitiative.exomiser.autoconfigure.genome.Hg38GenomeAnalysisServiceAutoConfiguration$$EnhancerBySpringCGLIB$$408163f2]: Constructor threw exception; nested exception is org.monarchinitiative.exomiser.autoconfigure.ExomiserAutoConfigurationException: Failed to load/find file /Users/admin/Desktop/exomiser-cli-12.1.0/data/2102_hg38/exomiser-cli-12.1.0/data/2102_hg38/gnomad.genomes.r3.0.indel.tsv. Please check exomiser properties file points to a valid tabix .gz file.
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:596)
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:90)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:374)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1395)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:592)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:515)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:849)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:877)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:549)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:775)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:316)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1260)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1248)
	at org.monarchinitiative.exomiser.cli.Main.main(Main.java:44)
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'analysisParser' defined in URL [jar:file:/Users/admin/Desktop/exomiser-cli-12.1.0/lib/exomiser-core-12.1.0.jar!/org/monarchinitiative/exomiser/core/analysis/AnalysisParser.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'genomeAnalysisServiceProvider' defined in class path resource [org/monarchinitiative/exomiser/autoconfigure/genome/GenomeAnalysisServiceAutoConfiguration.class]: Unsatisfied dependency expressed through method 'genomeAnalysisServiceProvider' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.monarchinitiative.exomiser.autoconfigure.genome.Hg38GenomeAnalysisServiceAutoConfiguration': Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.monarchinitiative.exomiser.autoconfigure.genome.Hg38GenomeAnalysisServiceAutoConfiguration$$EnhancerBySpringCGLIB$$408163f2]: Constructor threw exception; nested exception is org.monarchinitiative.exomiser.autoconfigure.ExomiserAutoConfigurationException: Failed to load/find file /Users/admin/Desktop/exomiser-cli-12.1.0/data/2102_hg38/exomiser-cli-12.1.0/data/2102_hg38/gnomad.genomes.r3.0.indel.tsv. Please check exomiser properties file points to a valid tabix .gz file.
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:769)
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:218)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1325)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1171)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:555)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:515)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:277)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1247)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1167)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:593)
	... 18 common frames omitted
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'genomeAnalysisServiceProvider' defined in class path resource [org/monarchinitiative/exomiser/autoconfigure/genome/GenomeAnalysisServiceAutoConfiguration.class]: Unsatisfied dependency expressed through method 'genomeAnalysisServiceProvider' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.monarchinitiative.exomiser.autoconfigure.genome.Hg38GenomeAnalysisServiceAutoConfiguration': Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.monarchinitiative.exomiser.autoconfigure.genome.Hg38GenomeAnalysisServiceAutoConfiguration$$EnhancerBySpringCGLIB$$408163f2]: Constructor threw exception; nested exception is org.monarchinitiative.exomiser.autoconfigure.ExomiserAutoConfigurationException: Failed to load/find file /Users/admin/Desktop/exomiser-cli-12.1.0/data/2102_hg38/exomiser-cli-12.1.0/data/2102_hg38/gnomad.genomes.r3.0.indel.tsv. Please check exomiser properties file points to a valid tabix .gz file.
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:769)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:509)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1305)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1144)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:555)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:515)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:277)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1247)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1167)
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:857)
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:760)
	... 31 common frames omitted
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.monarchinitiative.exomiser.autoconfigure.genome.Hg38GenomeAnalysisServiceAutoConfiguration': Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.monarchinitiative.exomiser.autoconfigure.genome.Hg38GenomeAnalysisServiceAutoConfiguration$$EnhancerBySpringCGLIB$$408163f2]: Constructor threw exception; nested exception is org.monarchinitiative.exomiser.autoconfigure.ExomiserAutoConfigurationException: Failed to load/find file /Users/admin/Desktop/exomiser-cli-12.1.0/data/2102_hg38/exomiser-cli-12.1.0/data/2102_hg38/gnomad.genomes.r3.0.indel.tsv. Please check exomiser properties file points to a valid tabix .gz file.
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:304)
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:285)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1325)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1171)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:555)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:515)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:392)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1305)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1144)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:555)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:515)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:277)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.addCandidateEntry(DefaultListableBeanFactory.java:1463)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.findAutowireCandidates(DefaultListableBeanFactory.java:1427)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveMultipleBeans(DefaultListableBeanFactory.java:1295)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1205)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1167)
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:857)
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:760)
	... 45 common frames omitted
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.monarchinitiative.exomiser.autoconfigure.genome.Hg38GenomeAnalysisServiceAutoConfiguration$$EnhancerBySpringCGLIB$$408163f2]: Constructor threw exception; nested exception is org.monarchinitiative.exomiser.autoconfigure.ExomiserAutoConfigurationException: Failed to load/find file /Users/admin/Desktop/exomiser-cli-12.1.0/data/2102_hg38/exomiser-cli-12.1.0/data/2102_hg38/gnomad.genomes.r3.0.indel.tsv. Please check exomiser properties file points to a valid tabix .gz file.
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:184)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:117)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:300)
	... 71 common frames omitted
Caused by: org.monarchinitiative.exomiser.autoconfigure.ExomiserAutoConfigurationException: Failed to load/find file /Users/admin/Desktop/exomiser-cli-12.1.0/data/2102_hg38/exomiser-cli-12.1.0/data/2102_hg38/gnomad.genomes.r3.0.indel.tsv. Please check exomiser properties file points to a valid tabix .gz file.
	at org.monarchinitiative.exomiser.autoconfigure.genome.TabixDataSourceLoader.load(TabixDataSourceLoader.java:50)
	at org.monarchinitiative.exomiser.autoconfigure.genome.GenomeDataSourceLoader.getTabixDataSourceOrDefault(GenomeDataSourceLoader.java:134)
	at org.monarchinitiative.exomiser.autoconfigure.genome.GenomeDataSourceLoader.<init>(GenomeDataSourceLoader.java:86)
	at org.monarchinitiative.exomiser.autoconfigure.genome.GenomeDataSourceLoader.load(GenomeDataSourceLoader.java:68)
	at org.monarchinitiative.exomiser.autoconfigure.genome.GenomeAnalysisServiceConfigurer.<init>(GenomeAnalysisServiceConfigurer.java:69)
	at org.monarchinitiative.exomiser.autoconfigure.genome.Hg38GenomeAnalysisServiceAutoConfiguration.<init>(Hg38GenomeAnalysisServiceAutoConfiguration.java:46)
	at org.monarchinitiative.exomiser.autoconfigure.genome.Hg38GenomeAnalysisServiceAutoConfiguration$$EnhancerBySpringCGLIB$$408163f2.<init>(<generated>)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:172)
	... 73 common frames omitted
Caused by: java.io.FileNotFoundException: /Users/admin/Desktop/exomiser-cli-12.1.0/data/2102_hg38/exomiser-cli-12.1.0/data/2102_hg38/gnomad.genomes.r3.0.indel.tsv (No such file or directory)
	at java.base/java.io.RandomAccessFile.open0(Native Method)
	at java.base/java.io.RandomAccessFile.open(RandomAccessFile.java:347)
	at java.base/java.io.RandomAccessFile.<init>(RandomAccessFile.java:261)
	at java.base/java.io.RandomAccessFile.<init>(RandomAccessFile.java:216)
	at htsjdk.samtools.seekablestream.SeekableFileStream.<init>(SeekableFileStream.java:47)
	at htsjdk.samtools.seekablestream.SeekableStreamFactory$DefaultSeekableStreamFactory.getStreamFor(SeekableStreamFactory.java:103)
	at htsjdk.samtools.seekablestream.SeekableStreamFactory$DefaultSeekableStreamFactory.getStreamFor(SeekableStreamFactory.java:77)
	at htsjdk.tribble.readers.TabixReader.<init>(TabixReader.java:109)
	at org.monarchinitiative.exomiser.autoconfigure.genome.TabixDataSourceLoader.load(TabixDataSourceLoader.java:48)
	... 85 common frames omitted

Help would be appreciated
Thank you in advance

**Comment by stereotypy** [comment]
I was having some issues getting started with paths too, you can see from the output

`Failed to load/find file /Users/admin/Desktop/exomiser-cli-12.1.0/data/2102_hg38/exomiser-cli-12.1.0/data/2102_hg38/gnomad.genomes.r3.0.indel.tsv.`

Your path is being doubled up, keep tweaking the paths/root dirs in the file to fix it, lots of trial and error, that's what I did.
