### ISSUE TITLE
Exomiser Web - Application run fails

### ISSUE THREAD

**Issue by stathispapachristos** [exomiser/Exomiser#400]
Hello, 

I am trying to run the Exomiser Web application but get the error "java.lang.IllegalArgumentException: genomeAnalysisServices cannot be empty" during context initialization.

I built the exomiser-web-12.1.0.jar file with mvn install. I placed the application.properties file in the same folder as the exomiser-web-12.1.0.jar file. In application.properties, I define the data directory:

exomiser.data-directory=/data/fast/exomizer/exomiser-cli-12.1.0/data/2102_hg19

I get the same error when I use this path instead:
exomiser.data-directory=/data/fast/exomizer/exomiser-cli-12.1.0/data 

The exomiser-client, which I downloaded from [https://exomiser.monarchinitiative.org/exomiser/download](url) runs smoothly. 

Does the error with the web app mean that it cannot locate the hg19 genome database? Any help is greately appreciated.

Thanks,
Stathis

Here is the shell output:

(base) papachristos@man2-dev001:~/projects/Exomiser/exomiser-web/target$ java -jar -XX:+UseG1GC -Xms8G -Xmx8G exomiser-web-12.1.0.jar
  _____ _            _____                     _
 |_   _| |__   ___  | ____|_  _____  _ __ ___ (_)___  ___ _ __
   | | | '_ \ / _ \ |  _| \ \/ / _ \| '_ ` _ \| / __|/ _ \ '__|
   | | | | | |  __/ | |___ >  < (_) | | | | | | \__ \  __/ |
   |_| |_| |_|\___| |_____/_/\_\___/|_| |_| |_|_|___/\___|_|

 === Web Server ===                              v12.1.0

2021-06-18 11:24:53.902  INFO 228750 --- [           main] o.m.exomiser.web.ExomiserWebApp          : Starting ExomiserWebApp on man2-dev001 with PID 228750 (/home/papachristos/projects/Exomiser/exomiser-web/target/exomiser-web-12.1.0.jar started by papachristos in /home/papachristos/projects/Exomiser/exomiser-web/target)
2021-06-18 11:24:53.905  INFO 228750 --- [           main] o.m.exomiser.web.ExomiserWebApp          : No active profile set, falling back to default profiles: default
2021-06-18 11:24:55.176  INFO 228750 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'org.springframework.transaction.annotation.ProxyTransactionManagementConfiguration' of type [org.springframework.transaction.annotation.ProxyTransactionManagementConfiguration$$EnhancerBySpringCGLIB$$9622ef3] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2021-06-18 11:24:55.490  INFO 228750 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 8090 (http)
2021-06-18 11:24:55.514  INFO 228750 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2021-06-18 11:24:55.514  INFO 228750 --- [           main] org.apache.catalina.core.StandardEngine  : Starting Servlet engine: [Apache Tomcat/9.0.16]
2021-06-18 11:24:55.523  INFO 228750 --- [           main] o.a.catalina.core.AprLifecycleListener   : The APR based Apache Tomcat Native library which allows optimal performance in production environments was not found on the java.library.path: [/usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib]
2021-06-18 11:24:55.580  INFO 228750 --- [           main] o.a.c.c.C.[.[localhost].[/exomiser]      : Initializing Spring embedded WebApplicationContext
2021-06-18 11:24:55.580  INFO 228750 --- [           main] o.s.web.context.ContextLoader            : Root WebApplicationContext: initialization completed in 1638 ms
2021-06-18 11:24:55.992  INFO 228750 --- [           main] o.m.e.web.config.ControllerConfig        : Set max variants to 100000
2021-06-18 11:24:55.994  INFO 228750 --- [           main] o.m.e.web.config.ControllerConfig        : Set max genes to 20
2021-06-18 11:24:55.996  INFO 228750 --- [           main] o.m.e.web.config.ControllerConfig        : Instance is running in a NON-CLINICAL setting.
2021-06-18 11:24:56.005  WARN 228750 --- [           main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'submitJobController': Unsatisfied dependency expressed through field 'exomiser'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'exomiser' defined in URL [jar:file:/home/papachristos/projects/Exomiser/exomiser-web/target/exomiser-web-12.1.0.jar!/BOOT-INF/lib/exomiser-core-12.1.0.jar!/org/monarchinitiative/exomiser/core/Exomiser.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'analysisFactory' defined in URL [jar:file:/home/papachristos/projects/Exomiser/exomiser-web/target/exomiser-web-12.1.0.jar!/BOOT-INF/lib/exomiser-core-12.1.0.jar!/org/monarchinitiative/exomiser/core/analysis/AnalysisFactory.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'genomeAnalysisServiceProvider' defined in class path resource [org/monarchinitiative/exomiser/autoconfigure/genome/GenomeAnalysisServiceAutoConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.monarchinitiative.exomiser.core.genome.GenomeAnalysisServiceProvider]: Factory method 'genomeAnalysisServiceProvider' threw exception; nested exception is java.lang.IllegalArgumentException: genomeAnalysisServices cannot be empty.
2021-06-18 11:24:56.008  INFO 228750 --- [           main] o.apache.catalina.core.StandardService   : Stopping service [Tomcat]
2021-06-18 11:24:56.022  INFO 228750 --- [           main] ConditionEvaluationReportLoggingListener :

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2021-06-18 11:24:56.025 ERROR 228750 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'submitJobController': Unsatisfied dependency expressed through field 'exomiser'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'exomiser' defined in URL [jar:file:/home/papachristos/projects/Exomiser/exomiser-web/target/exomiser-web-12.1.0.jar!/BOOT-INF/lib/exomiser-core-12.1.0.jar!/org/monarchinitiative/exomiser/core/Exomiser.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'analysisFactory' defined in URL [jar:file:/home/papachristos/projects/Exomiser/exomiser-web/target/exomiser-web-12.1.0.jar!/BOOT-INF/lib/exomiser-core-12.1.0.jar!/org/monarchinitiative/exomiser/core/analysis/AnalysisFactory.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'genomeAnalysisServiceProvider' defined in class path resource [org/monarchinitiative/exomiser/autoconfigure/genome/GenomeAnalysisServiceAutoConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.monarchinitiative.exomiser.core.genome.GenomeAnalysisServiceProvider]: Factory method 'genomeAnalysisServiceProvider' threw exception; nested exception is java.lang.IllegalArgumentException: genomeAnalysisServices cannot be empty.
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:596)
        at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:90)
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:374)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1395)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:592)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:515)
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:849)
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:877)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:549)
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:142)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:775)
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:316)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1260)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1248)
        at org.monarchinitiative.exomiser.web.ExomiserWebApp.main(ExomiserWebApp.java:33)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'exomiser' defined in URL [jar:file:/home/papachristos/projects/Exomiser/exomiser-web/target/exomiser-web-12.1.0.jar!/BOOT-INF/lib/exomiser-core-12.1.0.jar!/org/monarchinitiative/exomiser/core/Exomiser.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'analysisFactory' defined in URL [jar:file:/home/papachristos/projects/Exomiser/exomiser-web/target/exomiser-web-12.1.0.jar!/BOOT-INF/lib/exomiser-core-12.1.0.jar!/org/monarchinitiative/exomiser/core/analysis/AnalysisFactory.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'genomeAnalysisServiceProvider' defined in class path resource [org/monarchinitiative/exomiser/autoconfigure/genome/GenomeAnalysisServiceAutoConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.monarchinitiative.exomiser.core.genome.GenomeAnalysisServiceProvider]: Factory method 'genomeAnalysisServiceProvider' threw exception; nested exception is java.lang.IllegalArgumentException: genomeAnalysisServices cannot be empty.
        at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:769)
        at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:218)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1325)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1171)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:555)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:515)
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
        at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:277)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1247)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1167)
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:593)
        ... 27 common frames omitted
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'analysisFactory' defined in URL [jar:file:/home/papachristos/projects/Exomiser/exomiser-web/target/exomiser-web-12.1.0.jar!/BOOT-INF/lib/exomiser-core-12.1.0.jar!/org/monarchinitiative/exomiser/core/analysis/AnalysisFactory.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'genomeAnalysisServiceProvider' defined in class path resource [org/monarchinitiative/exomiser/autoconfigure/genome/GenomeAnalysisServiceAutoConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.monarchinitiative.exomiser.core.genome.GenomeAnalysisServiceProvider]: Factory method 'genomeAnalysisServiceProvider' threw exception; nested exception is java.lang.IllegalArgumentException: genomeAnalysisServices cannot be empty.
        at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:769)
        at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:218)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1325)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1171)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:555)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:515)
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
        at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:277)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1247)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1167)
        at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:857)
        at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:760)
        ... 40 common frames omitted
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'genomeAnalysisServiceProvider' defined in class path resource [org/monarchinitiative/exomiser/autoconfigure/genome/GenomeAnalysisServiceAutoConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.monarchinitiative.exomiser.core.genome.GenomeAnalysisServiceProvider]: Factory method 'genomeAnalysisServiceProvider' threw exception; nested exception is java.lang.IllegalArgumentException: genomeAnalysisServices cannot be empty.
        at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:627)
        at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:607)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1305)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1144)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:555)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:515)
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
        at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:277)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1247)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1167)
        at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:857)
        at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:760)
        ... 54 common frames omitted
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.monarchinitiative.exomiser.core.genome.GenomeAnalysisServiceProvider]: Factory method 'genomeAnalysisServiceProvider' threw exception; nested exception is java.lang.IllegalArgumentException: genomeAnalysisServices cannot be empty.
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185)
        at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:622)
        ... 68 common frames omitted
Caused by: java.lang.IllegalArgumentException: genomeAnalysisServices cannot be empty.
        at org.monarchinitiative.exomiser.core.genome.GenomeAnalysisServiceProvider.<init>(GenomeAnalysisServiceProvider.java:41)
        at org.monarchinitiative.exomiser.autoconfigure.genome.GenomeAnalysisServiceAutoConfiguration.genomeAnalysisServiceProvider(GenomeAnalysisServiceAutoConfiguration.java:51)
        at org.monarchinitiative.exomiser.autoconfigure.genome.GenomeAnalysisServiceAutoConfiguration$$EnhancerBySpringCGLIB$$7300c41.CGLIB$genomeAnalysisServiceProvider$0(<generated>)
        at org.monarchinitiative.exomiser.autoconfigure.genome.GenomeAnalysisServiceAutoConfiguration$$EnhancerBySpringCGLIB$$7300c41$$FastClassBySpringCGLIB$$2829d134.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244)
        at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:363)
        at org.monarchinitiative.exomiser.autoconfigure.genome.GenomeAnalysisServiceAutoConfiguration$$EnhancerBySpringCGLIB$$7300c41.genomeAnalysisServiceProvider(<generated>)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
        ... 69 common frames omitted

**Comment by rejwan052** [comment]
Hi @stathispapachristos I'm facing the same problem when running the exomiser-web application. Can you solve this problem?

**Comment by stathispapachristos** [comment]
Hello @rejwan052! According to a colleague who knows Java, one needs to provide the following 3 parameters in the command:
**--exomiser.data-directory**=/data/fast/exomizer/exomiser-cli-12.1.0/data/ 
**--exomiser.hg19.data-version**=2102 
**--exomiser.phenotype.data-version**=2102
