### ISSUE TITLE
Error creating bean with name 'dataSource' when running test example on exomiser-cli-13.0.0

### ISSUE THREAD

**Issue by evgonzal** [exomiser/Exomiser#412]
Good morning

I am getting the current error when running the example test after installing exomiser-cli-13.0.0 on a mac laptop:

I run:
java -Xms4g -Xmx8g -jar exomiser-cli-13.0.0.jar --analysis examples/test-analysis-exome.yml

I get:
 Welcome to:
  _____ _            _____                     _
 |_   _| |__   ___  | ____|_  _____  _ __ ___ (_)___  ___ _ __
   | | | '_ \ / _ \ |  _| \ \/ / _ \| '_ ` _ \| / __|/ _ \ '__|
   | | | | | |  __/ | |___ >  < (_) | | | | | | \__ \  __/ |
   |_| |_| |_|\___| |_____/_/\_\___/|_| |_| |_|_|___/\___|_|

 A Tool to Annotate and Prioritize Exome Variants     v13.0.0

2021-11-13 13:09:04.630  INFO 25107 --- [           main] org.monarchinitiative.exomiser.cli.Main  : Starting Main using Java 11.0.9.1 on MacBook-Pro.local with PID 25107 (/Users/Eva/BIOINFO/exomiser-cli-13.0.0/exomiser-cli-13.0.0.jar started by Eva in /Users/Eva/BIOINFO/exomiser-cli-13.0.0)
2021-11-13 13:09:04.634  INFO 25107 --- [           main] org.monarchinitiative.exomiser.cli.Main  : No active profile set, falling back to default profiles: default
2021-11-13 13:09:05.490  INFO 25107 --- [           main] o.m.exomiser.cli.config.MainConfig       : Exomiser home: /Users/Eva/BIOINFO/exomiser-cli-13.0.0
2021-11-13 13:09:05.500  INFO 25107 --- [           main] o.m.exomiser.cli.config.MainConfig       : Data source directory defined in properties as: ./data
2021-11-13 13:09:05.501  INFO 25107 --- [           main] o.m.exomiser.cli.config.MainConfig       : Root data source directory set to: /Users/Eva/BIOINFO/exomiser-cli-13.0.0/./data
2021-11-13 13:09:05.505  INFO 25107 --- [           main] o.m.e.c.g.j.JannovarDataProtoSerialiser  : Deserialising Jannovar data from /Users/Eva/BIOINFO/exomiser-cli-13.0.0/./data/2109_hg38/2109_hg38_transcripts_refseq.ser
2021-11-13 13:09:08.446  INFO 25107 --- [           main] o.m.e.c.g.j.JannovarDataProtoSerialiser  : Deserialisation took 2.94 sec.
2021-11-13 13:09:09.350  INFO 25107 --- [           main] o.m.e.c.g.dao.VariantWhiteListLoader     : Loading variant whitelist from: /Users/Eva/BIOINFO/exomiser-cli-13.0.0/./data/2109_hg38/2109_hg38_clinvar_whitelist.tsv.gz
2021-11-13 13:09:09.556  INFO 25107 --- [           main] o.m.e.c.g.dao.VariantWhiteListLoader     : Loaded 112277 variants into whitelist
2021-11-13 13:09:10.103  INFO 25107 --- [           main] g.GenomeAnalysisServiceAutoConfiguration : Configured hg38 genome analysis service
2021-11-13 13:09:11.399  INFO 25107 --- [           main] o.m.exomiser.cli.config.MainConfig       : Default results directory set to: /Users/Eva/BIOINFO/exomiser-cli-13.0.0/results
2021-11-13 13:09:11.443  WARN 25107 --- [           main] s.c.a.AnnotationConfigApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'dataSource' defined in class path resource [org/springframework/boot/autoconfigure/jdbc/DataSourceConfiguration$Hikari.class]: Unsatisfied dependency expressed through method 'dataSource' parameter 0; nested exception is org.springframework.beans.factory.NoUniqueBeanDefinitionException: No qualifying bean of type 'org.springframework.boot.autoconfigure.jdbc.DataSourceProperties' available: expected single matching bean but found 3: spring.datasource-org.springframework.boot.autoconfigure.jdbc.DataSourceProperties,phenotypeDataSourceProperties,hg38genomeDataSourceProperties
2021-11-13 13:09:11.490  INFO 25107 --- [           main] ConditionEvaluationReportLoggingListener : 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2021-11-13 13:09:11.508 ERROR 25107 --- [           main] o.s.b.d.LoggingFailureAnalysisReporter   : 

***************************
APPLICATION FAILED TO START
***************************

Description:

Parameter 0 of method dataSource in org.springframework.boot.autoconfigure.jdbc.DataSourceConfiguration$Hikari required a single bean, but 3 were found:
	- spring.datasource-org.springframework.boot.autoconfigure.jdbc.DataSourceProperties: defined in null
	- phenotypeDataSourceProperties: defined by method 'phenotypeDataSourceProperties' in org.monarchinitiative.exomiser.autoconfigure.phenotype.PhenotypeProperties
	- hg38genomeDataSourceProperties: defined by method 'hg38genomeDataSourceProperties' in org.monarchinitiative.exomiser.autoconfigure.genome.Hg38GenomeProperties

Action:

Consider marking one of the beans as @Primary, updating the consumer to accept multiple beans, or using @Qualifier to identify the bean that should be consumed

-------------------

How can I fix this problem?

Thanks in advance,

Eva

**Comment by julesjacobsen** [comment]
Hi Eva,

Are you trying to only load the hg38 and phenotype data? I've published [release 13.0.1](https://github.com/exomiser/Exomiser/releases/tag/13.0.1) with a fix for this now.

**Comment by evgonzal** [comment]
Dear Jules,

Thanks for your response. We have downloaded the new fixed version 13.0.1 but it seems that now I can get other errors. I am able at least to start running exomiser but now it throws an error in this step: ConditionEvaluationReportLoggingListener.

I paste the error I get. 

Thanks in advance for your help

Eva


java -Xms2g -Xmx4g -jar /Users/Eva/BIOINFO/exomiser-cli-13.0.1/exomiser-cli-13.0.1.jar --analysis /Users/Eva/BIOINFO/exomiser-cli-13.0.1/examples/test-analysis-exome.yml --spring.config.location=/Users/Eva/BIOINFO/exomiser-cli-13.0.1/application.properties

 Welcome to:
  _____ _            _____                     _
 |_   _| |__   ___  | ____|_  _____  _ __ ___ (_)___  ___ _ __
   | | | '_ \ / _ \ |  _| \ \/ / _ \| '_ ` _ \| / __|/ _ \ '__|
   | | | | | |  __/ | |___ >  < (_) | | | | | | \__ \  __/ |
   |_| |_| |_|\___| |_____/_/\_\___/|_| |_| |_|_|___/\___|_|

 A Tool to Annotate and Prioritize Exome Variants     v13.0.1

2021-11-24 19:18:51.234  INFO 36926 --- [           main] org.monarchinitiative.exomiser.cli.Main  : Starting Main using Java 11.0.9.1 on MacBook-Pro.local with PID 36926 (/Users/Eva/BIOINFO/exomiser-cli-13.0.1/exomiser-cli-13.0.1.jar started by Eva in /Users/Eva/BIOINFO)
2021-11-24 19:18:51.237  INFO 36926 --- [           main] org.monarchinitiative.exomiser.cli.Main  : No active profile set, falling back to default profiles: default
2021-11-24 19:18:52.034  INFO 36926 --- [           main] o.m.exomiser.cli.config.MainConfig       : Exomiser home: /Users/Eva/BIOINFO/exomiser-cli-13.0.1
2021-11-24 19:18:52.043  INFO 36926 --- [           main] o.m.exomiser.cli.config.MainConfig       : Data source directory defined in properties as: /Users/Eva/BIOINFO/exomiser-cli-13.0.1/data
2021-11-24 19:18:52.043  INFO 36926 --- [           main] o.m.exomiser.cli.config.MainConfig       : Root data source directory set to: /Users/Eva/BIOINFO/exomiser-cli-13.0.1/data
2021-11-24 19:18:52.048  INFO 36926 --- [           main] o.m.e.c.g.j.JannovarDataProtoSerialiser  : Deserialising Jannovar data from /Users/Eva/BIOINFO/exomiser-cli-13.0.1/data/2109_hg38/2109_hg38_transcripts_refseq.ser
2021-11-24 19:18:55.105  INFO 36926 --- [           main] o.m.e.c.g.j.JannovarDataProtoSerialiser  : Deserialisation took 3.056 sec.
2021-11-24 19:18:56.585  INFO 36926 --- [           main] o.m.e.c.g.dao.VariantWhiteListLoader     : Loading variant whitelist from: /Users/Eva/BIOINFO/exomiser-cli-13.0.1/data/2109_hg38/2109_hg38_clinvar_whitelist.tsv.gz
2021-11-24 19:18:56.896  INFO 36926 --- [           main] o.m.e.c.g.dao.VariantWhiteListLoader     : Loaded 112277 variants into whitelist
2021-11-24 19:18:57.527  INFO 36926 --- [           main] g.GenomeAnalysisServiceAutoConfiguration : Configured hg38 genome analysis service
2021-11-24 19:19:03.222  INFO 36926 --- [           main] o.m.exomiser.cli.config.MainConfig       : Default results directory set to: /Users/Eva/BIOINFO/exomiser-cli-13.0.1/results
2021-11-24 19:19:03.417  INFO 36926 --- [           main] org.monarchinitiative.exomiser.cli.Main  : Started Main in 12.799 seconds (JVM running for 13.191)
2021-11-24 19:19:03.768  INFO 36926 --- [           main] o.m.e.cli.ExomiserCommandLineRunner      : Exomiser running...
2021-11-24 19:19:03.777  INFO 36926 --- [           main] ConditionEvaluationReportLoggingListener : 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2021-11-24 19:19:03.796 ERROR 36926 --- [           main] o.s.boot.SpringApplication               : Application run failed

java.lang.IllegalStateException: Failed to execute CommandLineRunner
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:794)
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:775)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:345)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1343)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1332)
	at org.monarchinitiative.exomiser.cli.Main.main(Main.java:53)
Caused by: org.monarchinitiative.exomiser.core.genome.UnsupportedGenomeAssemblyException: Assembly hg19 not supported in this instance. Supported assemblies are: [hg38]
	at org.monarchinitiative.exomiser.core.analysis.JobParser.checkAssemblySupportedOrThrowException(JobParser.java:135)
	at org.monarchinitiative.exomiser.core.analysis.JobParser.parseSample(JobParser.java:86)
	at org.monarchinitiative.exomiser.core.analysis.AnalysisParser.parseSample(AnalysisParser.java:99)
	at org.monarchinitiative.exomiser.core.Exomiser.run(Exomiser.java:67)
	at org.monarchinitiative.exomiser.cli.ExomiserCommandLineRunner.runJob(ExomiserCommandLineRunner.java:79)
	at org.monarchinitiative.exomiser.cli.ExomiserCommandLineRunner.runJobs(ExomiserCommandLineRunner.java:62)
	at org.monarchinitiative.exomiser.cli.ExomiserCommandLineRunner.run(ExomiserCommandLineRunner.java:57)
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:791)
	... 5 common frames omitted

**Comment by julesjacobsen** [comment]
You're trying to analyse an hg19 sample on an Exomiser instance which only has hg38 data loaded. 

See the error:

```
Caused by: org.monarchinitiative.exomiser.core.genome.UnsupportedGenomeAssemblyException: Assembly hg19 not supported in this instance. Supported assemblies are: [hg38]
```

Check that the assembly is correct in the sample, or make sure you enable hg19 in the application.properties file. There is an example of this in the distribution.

**Comment by evgonzal** [comment]
Dear Jules,

You're right. I finally managed to run exomiser v13.0.1.

Thanks!

Eva
