### ISSUE TITLE
One sample from multi-sample VCF

### ISSUE THREAD

**Issue by C-Gouveia** [exomiser/Exomiser#413]
Hi! Is it possible to run Exomiser for one sample from a VCF with multiple samples?

I tried to run it by providing the proband ID but it errors that no pedigree file is available:

```at org.monarchinitiative.exomiser.core.analysis.util.PedigreeSampleValidator.createAndValidateSingleSamplePedigree(PedigreeSampleValidator.java:90)
	at org.monarchinitiative.exomiser.core.analysis.util.PedigreeSampleValidator.validate(PedigreeSampleValidator.java:72)
	at org.monarchinitiative.exomiser.core.analysis.AbstractAnalysisRunner.run(AbstractAnalysisRunner.java:82)
	at org.monarchinitiative.exomiser.core.Exomiser.run(Exomiser.java:64)
	at org.monarchinitiative.exomiser.cli.ExomiserCommandLineRunner.runAnalysisAndWriteResults(ExomiserCommandLineRunner.java:128)
	at org.monarchinitiative.exomiser.cli.ExomiserCommandLineRunner.runAnalysisFromScript(ExomiserCommandLineRunner.java:124)
	at org.monarchinitiative.exomiser.cli.ExomiserCommandLineRunner.runAnalyses(ExomiserCommandLineRunner.java:83)
	at org.monarchinitiative.exomiser.cli.ExomiserCommandLineRunner.run(ExomiserCommandLineRunner.java:74)
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:813)
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:797)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:324)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1260)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1248)
	at org.monarchinitiative.exomiser.cli.Main.main(Main.java:44)```

**Comment by julesjacobsen** [comment]
Sorry, no. You should be able to extract a single sample VCF using something like bcftools.
