### ISSUE TITLE
Assembly hg19 not supported in this instance. Supported assemblies are: [hg38]

### ISSUE THREAD

**Issue by LiviaMoura** [exomiser/Exomiser#429]
Hello...
I was trying to run exomiser docker on my hg38 VCF and I got the error title error.
What am I doing wrong?

### The error
```
A Tool to Annotate and Prioritize Exome Variants     v13.1.0-SNAPSHOT

2022-03-18 11:55:07.232  INFO 1 --- [           main] org.monarchinitiative.exomiser.cli.Main  : Starting Main using Java 17.0.1 on f98d87c18d0a with PID 1 (/app/classes started by root in /)
2022-03-18 11:55:07.234  INFO 1 --- [           main] org.monarchinitiative.exomiser.cli.Main  : No active profile set, falling back to default profiles: default
2022-03-18 11:55:08.047  INFO 1 --- [           main] o.m.exomiser.cli.config.MainConfig       : Exomiser home: /app/classes
2022-03-18 11:55:08.059  INFO 1 --- [           main] o.m.exomiser.cli.config.MainConfig       : Root data source directory set to: /data
2022-03-18 11:55:08.064  INFO 1 --- [           main] o.m.e.c.g.j.JannovarDataProtoSerialiser  : Deserialising Jannovar data from /data/2109_hg38/2109_hg38_transcripts_ensembl.ser
2022-03-18 11:55:09.579  INFO 1 --- [           main] o.m.e.c.g.j.JannovarDataProtoSerialiser  : Deserialisation took 1.515 sec.
2022-03-18 11:55:10.390  INFO 1 --- [           main] o.m.e.c.g.dao.VariantWhiteListLoader     : Loading variant whitelist from: /data/2109_hg38/2109_hg38_clinvar_whitelist.tsv.gz
2022-03-18 11:55:10.615  INFO 1 --- [           main] o.m.e.c.g.dao.VariantWhiteListLoader     : Loaded 112277 variants into whitelist
2022-03-18 11:55:11.427  INFO 1 --- [           main] g.GenomeAnalysisServiceAutoConfiguration : Configured hg38 genome analysis service
2022-03-18 11:55:17.539  INFO 1 --- [           main] o.m.exomiser.cli.config.MainConfig       : Default results directory set to: /app/classes/results
2022-03-18 11:55:17.564  INFO 1 --- [           main] o.m.e.a.ExomiserConfigReporter           : exomiser.data-directory: /data
2022-03-18 11:55:17.565  INFO 1 --- [           main] o.m.e.a.ExomiserConfigReporter           : exomiser.hg19.data-version: -
2022-03-18 11:55:17.566  INFO 1 --- [           main] o.m.e.a.ExomiserConfigReporter           : exomiser.hg38.data-version: 2109
2022-03-18 11:55:17.567  INFO 1 --- [           main] o.m.e.a.ExomiserConfigReporter           : exomiser.phenotype.data-version: 2109
2022-03-18 11:55:17.764  INFO 1 --- [           main] org.monarchinitiative.exomiser.cli.Main  : Started Main in 10.914 seconds (JVM running for 11.238)
2022-03-18 11:55:18.010  INFO 1 --- [           main] o.m.e.cli.ExomiserCommandLineRunner      : Exomiser running...
2022-03-18 11:55:18.017  INFO 1 --- [           main] ConditionEvaluationReportLoggingListener : 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2022-03-18 11:55:18.029 ERROR 1 --- [           main] o.s.boot.SpringApplication               : Application run failed

java.lang.IllegalStateException: Failed to execute CommandLineRunner
        at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:770)
        at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:751)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:309)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1301)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1290)
        at org.monarchinitiative.exomiser.cli.Main.main(Main.java:53)
Caused by: org.monarchinitiative.exomiser.core.genome.UnsupportedGenomeAssemblyException: Assembly hg19 not supported in this instance. Supported assemblies are: [hg38]
        at org.monarchinitiative.exomiser.core.analysis.JobParser.checkAssemblySupportedOrThrowException(JobParser.java:135)
        at org.monarchinitiative.exomiser.core.analysis.JobParser.parseSample(JobParser.java:86)
        at org.monarchinitiative.exomiser.core.analysis.AnalysisParser.parseSample(AnalysisParser.java:99)
        at org.monarchinitiative.exomiser.core.Exomiser.run(Exomiser.java:67)
        at org.monarchinitiative.exomiser.cli.ExomiserCommandLineRunner.runJob(ExomiserCommandLineRunner.java:79)
        at org.monarchinitiative.exomiser.cli.ExomiserCommandLineRunner.runJobs(ExomiserCommandLineRunner.java:62)
        at org.monarchinitiative.exomiser.cli.ExomiserCommandLineRunner.run(ExomiserCommandLineRunner.java:57)
        at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:767)
        ... 5 common frames omitted
```

### my application.properties
Note that I set only hg38 db

```
## exomiser root data directory ##
# root path where data is to be downloaded and worked on it is assumed that all the files required by exomiser listed
# in this properties file will be found in the data directory, unless specifically overridden here.
exomiser.data-directory=/data

### hg38 assembly ###
# To enable analysis of samples called against the hg38 assembly copy the hg19 above and just replace the hg19 with hg38
exomiser.hg38.data-version=2109
exomiser.hg38.data-directory=${exomiser.data-directory}/${exomiser.hg38.data-version}_hg38
#exomiser.hg38.cadd-snv-path=${exomiser.data-directory}/cadd/${cadd.version}/whole_genome_SNVs.tsv.gz
#exomiser.hg38.cadd-in-del-path=${exomiser.data-directory}/cadd/${cadd.version}/InDels.tsv.gz
#exomiser.hg38.remm-path=${exomiser.data-directory}/remm/ReMM.v${remm.version}.hg38.tsv.gz
#exomiser.hg38.local-frequency-path=${exomiser.data-directory}/local/local_frequency_test_hg38.tsv.gz
exomiser.hg38.variant-white-list-path=${exomiser.hg38.data-version}_hg38_clinvar_whitelist.tsv.gz

### phenotypes ###
exomiser.phenotype.data-version=2109
exomiser.phenotype.data-directory=${exomiser.data-directory}/${exomiser.phenotype.data-version}_phenotype
# String random walk data file
#exomiser.phenotype.random-walk-file-name=rw_string_10.mv
#exomiser.phenotype.random-walk-index-file-name=rw_string_9_05_id2index.gz
```

**Comment by julesjacobsen** [comment]
You need to specify that the assembly of the sample you are running is hg38 in the yaml input or on the command line via `--assembly hg38`. 

Exomiser currently defaults to hg19 if you don't specify anything.

**Comment by LiviaMoura** [comment]
ah, thank you very much... It worked :)
