### ISSUE TITLE
`java.nio.file.AccessDeniedException: /app/classes/results` / empty results

### ISSUE THREAD

**Issue by matentzn** [exomiser/Exomiser#555]
I am trying to exomise:

```
docker run -it \
                -v "/Users/matentzn/Dropbox/health/exomiser_analysis/exomiser-data:/exomiser-data" \
                -v "/Users/matentzn/Dropbox/health/exomiser_analysis/exomiser-config/:/exomiser" \
                -v "/Users/matentzn/Dropbox/health/exomiser_analysis/exomiser-results:/results" \
                exomiser/exomiser-cli:14.0.0 \
                --sample /exomiser/x-phenopacket.yml \
                --analysis /exomiser/x-analysis.yml \
                --spring.config.location=/exomiser/application.properties
```

But the results dir is empty and I get an error which I can't quite understand:

```
java.nio.file.AccessDeniedException: /app/classes/results
        at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:90) ~[na:na]
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106) ~[na:na]
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111) ~[na:na]
```

<details><summary>Full log here</summary>

```
 Welcome to:
  _____ _            _____                     _
 |_   _| |__   ___  | ____|_  _____  _ __ ___ (_)___  ___ _ __
   | | | '_ \ / _ \ |  _| \ \/ / _ \| '_ ` _ \| / __|/ _ \ '__|
   | | | | | |  __/ | |___ >  < (_) | | | | | | \__ \  __/ |
   |_| |_| |_|\___| |_____/_/\_\___/|_| |_| |_|_|___/\___|_|

 A Tool to Annotate and Prioritize Exome Variants     v14.0.0

2024-03-24T13:04:29.647Z  INFO 1 --- [           main] o.monarchinitiative.exomiser.cli.Main    : Starting Main using Java 17.0.6 with PID 1 (/app/classes started by nonroot in /home/nonroot)
2024-03-24T13:04:29.650Z  INFO 1 --- [           main] o.monarchinitiative.exomiser.cli.Main    : No active profile set, falling back to 1 default profile: "default"
2024-03-24T13:04:30.091Z  INFO 1 --- [           main] o.m.exomiser.cli.config.MainConfig       : Exomiser home: /app/classes
2024-03-24T13:04:30.098Z  INFO 1 --- [           main] o.m.exomiser.cli.config.MainConfig       : Root data source directory set to: /exomiser-data
2024-03-24T13:04:30.100Z  INFO 1 --- [           main] o.m.e.c.g.j.JannovarDataProtoSerialiser  : Deserialising Jannovar data from /exomiser-data/2402_hg19/2402_hg19_transcripts_ensembl.ser
2024-03-24T13:04:30.662Z  INFO 1 --- [           main] o.m.e.c.g.j.JannovarDataProtoSerialiser  : Deserialisation took 0.561 sec.
2024-03-24T13:04:31.108Z  INFO 1 --- [           main] o.m.e.c.g.dao.ClinVarWhiteListReader     : Reading ClinVar whitelist...
2024-03-24T13:04:31.112Z  INFO 1 --- [           main] o.m.e.c.g.dao.serialisers.MvStoreUtil    : MVMap 'clinvar' opened with 2353837 entries
2024-03-24T13:04:32.216Z  INFO 1 --- [           main] o.m.e.c.g.dao.ClinVarWhiteListReader     : Read 203570 ClinVar whitelist variants in 1108 ms
2024-03-24T13:04:32.229Z  INFO 1 --- [           main] o.m.e.a.genome.GenomeDataSourceLoader    : Loaded 203570 whitelist variants
2024-03-24T13:04:32.281Z  INFO 1 --- [           main] o.m.e.c.g.dao.serialisers.MvStoreUtil    : MVMap 'alleles' opened with 826441620 entries
2024-03-24T13:04:32.292Z  INFO 1 --- [           main] o.m.e.c.g.dao.serialisers.MvStoreUtil    : MVMap 'clinvar' opened with 2353837 entries
2024-03-24T13:04:32.618Z  INFO 1 --- [           main] g.GenomeAnalysisServiceAutoConfiguration : Configured hg19 genome analysis service
2024-03-24T13:04:33.241Z ERROR 1 --- [           main] o.m.exomiser.cli.config.MainConfig       : Unable to create default output directory for results /app/classes/results

java.nio.file.AccessDeniedException: /app/classes/results
        at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:90) ~[na:na]
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106) ~[na:na]
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111) ~[na:na]
        at java.base/sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:397) ~[na:na]
        at java.base/java.nio.file.Files.createDirectory(Files.java:700) ~[na:na]
        at org.monarchinitiative.exomiser.cli.config.MainConfig.resultsDir(MainConfig.java:66) ~[classes/:na]
        at org.monarchinitiative.exomiser.cli.config.MainConfig$$SpringCGLIB$$0.CGLIB$resultsDir$1(<generated>) ~[classes/:na]
        at org.monarchinitiative.exomiser.cli.config.MainConfig$$SpringCGLIB$$FastClass$$1.invoke(<generated>) ~[classes/:na]
        at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:258) ~[spring-core-6.1.4.jar:6.1.4]
        at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:331) ~[spring-context-6.1.4.jar:6.1.4]
        at org.monarchinitiative.exomiser.cli.config.MainConfig$$SpringCGLIB$$0.resultsDir(<generated>) ~[classes/:na]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[na:na]
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
        at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:140) ~[spring-beans-6.1.4.jar:6.1.4]
        at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:647) ~[spring-beans-6.1.4.jar:6.1.4]
        at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:639) ~[spring-beans-6.1.4.jar:6.1.4]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1335) ~[spring-beans-6.1.4.jar:6.1.4]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1165) ~[spring-beans-6.1.4.jar:6.1.4]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:562) ~[spring-beans-6.1.4.jar:6.1.4]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:522) ~[spring-beans-6.1.4.jar:6.1.4]
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:325) ~[spring-beans-6.1.4.jar:6.1.4]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-6.1.4.jar:6.1.4]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:323) ~[spring-beans-6.1.4.jar:6.1.4]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199) ~[spring-beans-6.1.4.jar:6.1.4]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:975) ~[spring-beans-6.1.4.jar:6.1.4]
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:959) ~[spring-context-6.1.4.jar:6.1.4]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:624) ~[spring-context-6.1.4.jar:6.1.4]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:754) ~[spring-boot-3.2.3.jar:3.2.3]
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:456) ~[spring-boot-3.2.3.jar:3.2.3]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:334) ~[spring-boot-3.2.3.jar:3.2.3]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1354) ~[spring-boot-3.2.3.jar:3.2.3]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1343) ~[spring-boot-3.2.3.jar:3.2.3]
        at org.monarchinitiative.exomiser.cli.Main.main(Main.java:53) ~[classes/:na]

2024-03-24T13:04:33.242Z  INFO 1 --- [           main] o.m.exomiser.cli.config.MainConfig       : Default results directory set to: /app/classes/results
2024-03-24T13:04:33.250Z  INFO 1 --- [           main] o.m.e.a.ExomiserConfigReporter           : exomiser.data-directory: /exomiser-data
2024-03-24T13:04:33.250Z  INFO 1 --- [           main] o.m.e.a.ExomiserConfigReporter           : exomiser.hg19.data-version: 2402
2024-03-24T13:04:33.250Z  INFO 1 --- [           main] o.m.e.a.ExomiserConfigReporter           : exomiser.hg19.clinvar-data-version: 2402
2024-03-24T13:04:33.250Z  INFO 1 --- [           main] o.m.e.a.ExomiserConfigReporter           : exomiser.hg38.data-version: -
2024-03-24T13:04:33.250Z  INFO 1 --- [           main] o.m.e.a.ExomiserConfigReporter           : exomiser.phenotype.data-version: 2402
2024-03-24T13:04:33.350Z  INFO 1 --- [           main] o.monarchinitiative.exomiser.cli.Main    : Started Main in 3.935 seconds (process running for 4.103)
2024-03-24T13:04:33.518Z  INFO 1 --- [           main] o.m.e.cli.ExomiserCommandLineRunner      : Exomiser running...
2024-03-24T13:04:33.528Z  INFO 1 --- [           main] o.m.exomiser.core.Exomiser               : Running analysis using hg19 assembly with mode: PASS_ONLY
2024-03-24T13:04:33.530Z  INFO 1 --- [           main] o.m.e.c.analysis.AbstractAnalysisRunner  : Validating sample input data
2024-03-24T13:04:33.551Z  INFO 1 --- [           main] o.m.e.c.analysis.AbstractAnalysisRunner  : Running analysis for proband 23ES_427 (sample 1 in VCF) from samples: [23ES_427]. Using coordinates for genome assembly hg19.
2024-03-24T13:04:33.687Z  INFO 1 --- [           main] o.m.e.c.analysis.AbstractAnalysisRunner  : Filtering variants with:
2024-03-24T13:04:33.688Z  INFO 1 --- [           main] o.m.e.c.analysis.AbstractAnalysisRunner  : FailedVariantFilter{}
2024-03-24T13:04:33.688Z  INFO 1 --- [           main] o.m.e.c.analysis.AbstractAnalysisRunner  : VariantEffectFilter{offTargetVariantTypes=[CODING_TRANSCRIPT_INTRON_VARIANT, FIVE_PRIME_UTR_EXON_VARIANT, THREE_PRIME_UTR_EXON_VARIANT, FIVE_PRIME_UTR_INTRON_VARIANT, THREE_PRIME_UTR_INTRON_VARIANT, NON_CODING_TRANSCRIPT_EXON_VARIANT, NON_CODING_TRANSCRIPT_INTRON_VARIANT, UPSTREAM_GENE_VARIANT, DOWNSTREAM_GENE_VARIANT, INTERGENIC_VARIANT, REGULATORY_REGION_VARIANT]}
2024-03-24T13:04:33.688Z  INFO 1 --- [           main] o.m.e.c.analysis.AbstractAnalysisRunner  : FrequencyFilter{maxFreq=2.0}
2024-03-24T13:04:33.689Z  INFO 1 --- [           main] o.m.e.c.analysis.AbstractAnalysisRunner  : Wrapping FrequencyFilter{maxFreq=2.0} with VariantDataProvider for sources [UK10K, GNOMAD_E_AFR, GNOMAD_E_AMR, GNOMAD_E_EAS, GNOMAD_E_NFE, GNOMAD_E_SAS, GNOMAD_G_AFR, GNOMAD_G_AMR, GNOMAD_G_EAS, GNOMAD_G_NFE, GNOMAD_G_SAS]
2024-03-24T13:04:33.689Z  INFO 1 --- [           main] o.m.e.c.analysis.AbstractAnalysisRunner  : PathogenicityFilter{keepNonPathogenic=true}
2024-03-24T13:04:33.689Z  INFO 1 --- [           main] o.m.e.c.analysis.AbstractAnalysisRunner  : Wrapping PathogenicityFilter{keepNonPathogenic=true} with VariantDataProvider for sources [REVEL, MVP]
2024-03-24T13:04:33.690Z  INFO 1 --- [           main] o.m.e.core.genome.VariantFactoryImpl     : Annotating variant records, trimming sequences and normalising positions...
2024-03-24T13:04:41.541Z  INFO 1 --- [           main] o.m.e.c.analysis.AbstractAnalysisRunner  : Loaded 100000 variants - 1073 passed variant filters...
2024-03-24T13:04:43.379Z  INFO 1 --- [           main] o.m.e.core.genome.VariantFactoryImpl     : Processed 148233 variant records into 125975 single allele variants (including 0 structural variants), 1149 are missing annotations, most likely due to non-numeric chromosome designations
2024-03-24T13:04:43.380Z  INFO 1 --- [           main] o.m.e.core.genome.VariantFactoryImpl     : Variant annotation finished in 0m 9s 689ms (9689 ms)
2024-03-24T13:04:43.380Z  INFO 1 --- [           main] o.m.e.c.analysis.AbstractAnalysisRunner  : Loaded 127124 variants - 1373 passed variant filters
2024-03-24T13:04:43.385Z  INFO 1 --- [           main] o.m.e.c.analysis.AbstractAnalysisRunner  : Checking inheritance mode compatibility with [AUTOSOMAL_DOMINANT, AUTOSOMAL_RECESSIVE, X_RECESSIVE, X_DOMINANT, MITOCHONDRIAL] for genes which passed filters
2024-03-24T13:04:43.430Z  INFO 1 --- [           main] o.m.e.c.analysis.AbstractAnalysisRunner  : Running GeneFilter: InheritanceFilter{compatibleModes=[AUTOSOMAL_DOMINANT, AUTOSOMAL_RECESSIVE, X_RECESSIVE, X_DOMINANT, MITOCHONDRIAL]}
2024-03-24T13:04:43.443Z  INFO 1 --- [           main] o.m.e.c.analysis.AbstractAnalysisRunner  : Running Prioritiser: OmimPrioritiser{}
2024-03-24T13:04:43.838Z  INFO 1 --- [           main] o.m.e.c.analysis.AbstractAnalysisRunner  : Running Prioritiser: HiPhivePriority{options=HiPhiveOptions{diseaseId='', candidateGeneSymbol='', benchmarkingEnabled=false, runPpi=true, runHuman=true, runMouse=true, runFish=true}}
2024-03-24T13:04:45.076Z  INFO 1 --- [           main] o.m.e.c.analysis.AbstractAnalysisRunner  : Variant filter stats are:
2024-03-24T13:04:45.076Z  INFO 1 --- [           main] o.m.e.c.analysis.AbstractAnalysisRunner  : FAILED_VARIANT_FILTER: pass=125975 fail=0
2024-03-24T13:04:45.076Z  INFO 1 --- [           main] o.m.e.c.analysis.AbstractAnalysisRunner  : VARIANT_EFFECT_FILTER: pass=27780 fail=98195
2024-03-24T13:04:45.076Z  INFO 1 --- [           main] o.m.e.c.analysis.AbstractAnalysisRunner  : FREQUENCY_FILTER: pass=1373 fail=26407
2024-03-24T13:04:45.076Z  INFO 1 --- [           main] o.m.e.c.analysis.AbstractAnalysisRunner  : PATHOGENICITY_FILTER: pass=1373 fail=0
2024-03-24T13:04:45.076Z  INFO 1 --- [           main] o.m.e.c.analysis.AbstractAnalysisRunner  : INHERITANCE_FILTER: pass=867 fail=506
2024-03-24T13:04:46.144Z  INFO 1 --- [           main] o.m.e.c.analysis.AbstractAnalysisRunner  : Scoring genes
2024-03-24T13:04:46.433Z  INFO 1 --- [           main] o.m.e.c.analysis.AbstractAnalysisRunner  : Analysed sample 23ES_427 with 562 genes containing 867 filtered variants
2024-03-24T13:04:46.433Z  INFO 1 --- [           main] o.m.e.c.analysis.AbstractAnalysisRunner  : Finished analysis in 0m 12s 882ms (12882 ms)
2024-03-24T13:04:46.433Z  INFO 1 --- [           main] o.m.e.cli.ExomiserCommandLineRunner      : Writing results...
2024-03-24T13:04:47.321Z  INFO 1 --- [           main] o.monarchinitiative.exomiser.cli.Main    : Exomising finished - Bye!
```
</details>

Any help much appreciated.

**Comment by matentzn** [comment]
I got the docker instructions from [you tutorial](https://oboacademy.github.io/obook/tutorial/exomiser-tutorial/#running-via-docker).

If I change the results dir:

```
docker run -it \
		-v "$(PWD)/exomiser-data:/exomiser-data" \
		-v "$(PWD)/exomiser-config/:/exomiser" \
		-v "$(PWD)/exomiser-results:/app/classes/results" \
		exomiser/exomiser-cli:14.0.0 \
		--sample /exomiser/myrto-phenopacket.yml \
		--analysis /exomiser/myrto-analysis.yml \
		--spring.config.location=/exomiser/application.properties
```

The error is not thrown, but still, no results are generated.

<details><summary>Full log</summary>

```
A Tool to Annotate and Prioritize Exome Variants     v14.0.0

2024-03-24T13:11:48.394Z  INFO 1 --- [           main] o.monarchinitiative.exomiser.cli.Main    : Starting Main using Java 17.0.6 with PID 1 (/app/classes started by nonroot in /home/nonroot)
2024-03-24T13:11:48.396Z  INFO 1 --- [           main] o.monarchinitiative.exomiser.cli.Main    : No active profile set, falling back to 1 default profile: "default"
2024-03-24T13:11:48.892Z  INFO 1 --- [           main] o.m.exomiser.cli.config.MainConfig       : Exomiser home: /app/classes
2024-03-24T13:11:48.900Z  INFO 1 --- [           main] o.m.exomiser.cli.config.MainConfig       : Root data source directory set to: /exomiser-data
2024-03-24T13:11:48.902Z  INFO 1 --- [           main] o.m.e.c.g.j.JannovarDataProtoSerialiser  : Deserialising Jannovar data from /exomiser-data/2402_hg19/2402_hg19_transcripts_ensembl.ser
2024-03-24T13:11:49.635Z  INFO 1 --- [           main] o.m.e.c.g.j.JannovarDataProtoSerialiser  : Deserialisation took 0.732 sec.
2024-03-24T13:11:50.215Z  INFO 1 --- [           main] o.m.e.c.g.dao.ClinVarWhiteListReader     : Reading ClinVar whitelist...
2024-03-24T13:11:50.220Z  INFO 1 --- [           main] o.m.e.c.g.dao.serialisers.MvStoreUtil    : MVMap 'clinvar' opened with 2353837 entries
2024-03-24T13:11:52.028Z  INFO 1 --- [           main] o.m.e.c.g.dao.ClinVarWhiteListReader     : Read 203570 ClinVar whitelist variants in 1812 ms
2024-03-24T13:11:52.051Z  INFO 1 --- [           main] o.m.e.a.genome.GenomeDataSourceLoader    : Loaded 203570 whitelist variants
2024-03-24T13:11:52.117Z  INFO 1 --- [           main] o.m.e.c.g.dao.serialisers.MvStoreUtil    : MVMap 'alleles' opened with 826441620 entries
2024-03-24T13:11:52.129Z  INFO 1 --- [           main] o.m.e.c.g.dao.serialisers.MvStoreUtil    : MVMap 'clinvar' opened with 2353837 entries
2024-03-24T13:11:52.557Z  INFO 1 --- [           main] g.GenomeAnalysisServiceAutoConfiguration : Configured hg19 genome analysis service
2024-03-24T13:11:53.334Z  INFO 1 --- [           main] o.m.exomiser.cli.config.MainConfig       : Default results directory set to: /app/classes/results
2024-03-24T13:11:53.343Z  INFO 1 --- [           main] o.m.e.a.ExomiserConfigReporter           : exomiser.data-directory: /exomiser-data
2024-03-24T13:11:53.343Z  INFO 1 --- [           main] o.m.e.a.ExomiserConfigReporter           : exomiser.hg19.data-version: 2402
2024-03-24T13:11:53.343Z  INFO 1 --- [           main] o.m.e.a.ExomiserConfigReporter           : exomiser.hg19.clinvar-data-version: 2402
2024-03-24T13:11:53.343Z  INFO 1 --- [           main] o.m.e.a.ExomiserConfigReporter           : exomiser.hg38.data-version: -
2024-03-24T13:11:53.343Z  INFO 1 --- [           main] o.m.e.a.ExomiserConfigReporter           : exomiser.phenotype.data-version: 2402
2024-03-24T13:11:53.437Z  INFO 1 --- [           main] o.monarchinitiative.exomiser.cli.Main    : Started Main in 5.247 seconds (process running for 5.454)
2024-03-24T13:11:53.607Z  INFO 1 --- [           main] o.m.e.cli.ExomiserCommandLineRunner      : Exomiser running...
2024-03-24T13:11:53.615Z  INFO 1 --- [           main] o.m.exomiser.core.Exomiser               : Running analysis using hg19 assembly with mode: PASS_ONLY
2024-03-24T13:11:53.618Z  INFO 1 --- [           main] o.m.e.c.analysis.AbstractAnalysisRunner  : Validating sample input data
2024-03-24T13:11:53.641Z  INFO 1 --- [           main] o.m.e.c.analysis.AbstractAnalysisRunner  : Running analysis for proband 23ES_427 (sample 1 in VCF) from samples: [23ES_427]. Using coordinates for genome assembly hg19.
2024-03-24T13:11:53.845Z  INFO 1 --- [           main] o.m.e.c.analysis.AbstractAnalysisRunner  : Filtering variants with:
2024-03-24T13:11:53.845Z  INFO 1 --- [           main] o.m.e.c.analysis.AbstractAnalysisRunner  : FailedVariantFilter{}
2024-03-24T13:11:53.845Z  INFO 1 --- [           main] o.m.e.c.analysis.AbstractAnalysisRunner  : VariantEffectFilter{offTargetVariantTypes=[CODING_TRANSCRIPT_INTRON_VARIANT, FIVE_PRIME_UTR_EXON_VARIANT, THREE_PRIME_UTR_EXON_VARIANT, FIVE_PRIME_UTR_INTRON_VARIANT, THREE_PRIME_UTR_INTRON_VARIANT, NON_CODING_TRANSCRIPT_EXON_VARIANT, NON_CODING_TRANSCRIPT_INTRON_VARIANT, UPSTREAM_GENE_VARIANT, DOWNSTREAM_GENE_VARIANT, INTERGENIC_VARIANT, REGULATORY_REGION_VARIANT]}
2024-03-24T13:11:53.846Z  INFO 1 --- [           main] o.m.e.c.analysis.AbstractAnalysisRunner  : FrequencyFilter{maxFreq=2.0}
2024-03-24T13:11:53.846Z  INFO 1 --- [           main] o.m.e.c.analysis.AbstractAnalysisRunner  : Wrapping FrequencyFilter{maxFreq=2.0} with VariantDataProvider for sources [UK10K, GNOMAD_E_AFR, GNOMAD_E_AMR, GNOMAD_E_EAS, GNOMAD_E_NFE, GNOMAD_E_SAS, GNOMAD_G_AFR, GNOMAD_G_AMR, GNOMAD_G_EAS, GNOMAD_G_NFE, GNOMAD_G_SAS]
2024-03-24T13:11:53.847Z  INFO 1 --- [           main] o.m.e.c.analysis.AbstractAnalysisRunner  : PathogenicityFilter{keepNonPathogenic=true}
2024-03-24T13:11:53.847Z  INFO 1 --- [           main] o.m.e.c.analysis.AbstractAnalysisRunner  : Wrapping PathogenicityFilter{keepNonPathogenic=true} with VariantDataProvider for sources [REVEL, MVP]
2024-03-24T13:11:53.847Z  INFO 1 --- [           main] o.m.e.core.genome.VariantFactoryImpl     : Annotating variant records, trimming sequences and normalising positions...
2024-03-24T13:12:01.718Z  INFO 1 --- [           main] o.m.e.c.analysis.AbstractAnalysisRunner  : Loaded 100000 variants - 1073 passed variant filters...
2024-03-24T13:12:03.654Z  INFO 1 --- [           main] o.m.e.core.genome.VariantFactoryImpl     : Processed 148233 variant records into 125975 single allele variants (including 0 structural variants), 1149 are missing annotations, most likely due to non-numeric chromosome designations
2024-03-24T13:12:03.655Z  INFO 1 --- [           main] o.m.e.core.genome.VariantFactoryImpl     : Variant annotation finished in 0m 9s 806ms (9806 ms)
2024-03-24T13:12:03.655Z  INFO 1 --- [           main] o.m.e.c.analysis.AbstractAnalysisRunner  : Loaded 127124 variants - 1373 passed variant filters
2024-03-24T13:12:03.660Z  INFO 1 --- [           main] o.m.e.c.analysis.AbstractAnalysisRunner  : Checking inheritance mode compatibility with [AUTOSOMAL_DOMINANT, AUTOSOMAL_RECESSIVE, X_RECESSIVE, X_DOMINANT, MITOCHONDRIAL] for genes which passed filters
2024-03-24T13:12:03.704Z  INFO 1 --- [           main] o.m.e.c.analysis.AbstractAnalysisRunner  : Running GeneFilter: InheritanceFilter{compatibleModes=[AUTOSOMAL_DOMINANT, AUTOSOMAL_RECESSIVE, X_RECESSIVE, X_DOMINANT, MITOCHONDRIAL]}
2024-03-24T13:12:03.716Z  INFO 1 --- [           main] o.m.e.c.analysis.AbstractAnalysisRunner  : Running Prioritiser: OmimPrioritiser{}
2024-03-24T13:12:04.222Z  INFO 1 --- [           main] o.m.e.c.analysis.AbstractAnalysisRunner  : Running Prioritiser: HiPhivePriority{options=HiPhiveOptions{diseaseId='', candidateGeneSymbol='', benchmarkingEnabled=false, runPpi=true, runHuman=true, runMouse=true, runFish=true}}
2024-03-24T13:12:05.405Z  INFO 1 --- [           main] o.m.e.c.analysis.AbstractAnalysisRunner  : Variant filter stats are:
2024-03-24T13:12:05.405Z  INFO 1 --- [           main] o.m.e.c.analysis.AbstractAnalysisRunner  : FAILED_VARIANT_FILTER: pass=125975 fail=0
2024-03-24T13:12:05.405Z  INFO 1 --- [           main] o.m.e.c.analysis.AbstractAnalysisRunner  : VARIANT_EFFECT_FILTER: pass=27780 fail=98195
2024-03-24T13:12:05.405Z  INFO 1 --- [           main] o.m.e.c.analysis.AbstractAnalysisRunner  : FREQUENCY_FILTER: pass=1373 fail=26407
2024-03-24T13:12:05.405Z  INFO 1 --- [           main] o.m.e.c.analysis.AbstractAnalysisRunner  : PATHOGENICITY_FILTER: pass=1373 fail=0
2024-03-24T13:12:05.405Z  INFO 1 --- [           main] o.m.e.c.analysis.AbstractAnalysisRunner  : INHERITANCE_FILTER: pass=867 fail=506
2024-03-24T13:12:06.504Z  INFO 1 --- [           main] o.m.e.c.analysis.AbstractAnalysisRunner  : Scoring genes
2024-03-24T13:12:06.782Z  INFO 1 --- [           main] o.m.e.c.analysis.AbstractAnalysisRunner  : Analysed sample 23ES_427 with 562 genes containing 867 filtered variants
2024-03-24T13:12:06.783Z  INFO 1 --- [           main] o.m.e.c.analysis.AbstractAnalysisRunner  : Finished analysis in 0m 13s 141ms (13141 ms)
2024-03-24T13:12:06.783Z  INFO 1 --- [           main] o.m.e.cli.ExomiserCommandLineRunner      : Writing results...
2024-03-24T13:12:07.721Z  INFO 1 --- [           main] o.monarchinitiative.exomiser.cli.Main    : Exomising finished - Bye!
```

</details>

**Comment by lpsyy** [comment]
in the first section, the program prompts “java.nio.file.AccessDeniedException: /app/classes/results”，maybe the file permission should change.

**Comment by matentzn** [comment]
Thanks @lpsyy the error is gone now but the results dir remains empty!

**Comment by matentzn** [comment]
@yaseminbridges sorted it out for me! I was missing the --output-dir option!

```
docker run -it \
                -v "/Users/matentzn/Dropbox/health/exomiser_analysis/exomiser-data:/exomiser-data" \
                -v "/Users/matentzn/Dropbox/health/exomiser_analysis/exomiser-config/:/exomiser" \
                -v "/Users/matentzn/Dropbox/health/exomiser_analysis/exomiser-results:/results" \
                exomiser/exomiser-cli:14.0.0 \
                --sample /exomiser/x-phenopacket.yml \
                --analysis /exomiser/x-analysis.yml \
                --output-directory /results \
                --spring.config.location=/exomiser/application.properties
```

Thanks all!
