### ISSUE TITLE
java.lang.IllegalArgumentException: Unable to parse sample from file

### ISSUE THREAD

**Issue by Peter-J-Freeman** [exomiser/Exomiser#579]
Not sure if I have configured incorrectly but I am getting this error from all job files including the pre-set tests

```
 A Tool to Annotate and Prioritize Exome Variants     v14.0.2

2024-11-27T11:34:45.657Z  INFO 2030681 --- [           main] o.monarchinitiative.exomiser.cli.Main    : Starting Main using Java 17.0.13 with PID 2030681 (/home/e05374pc/exomiser/exomiser-cli-14.0.2/exomiser-cli-14.0.2.jar started by e05374pc in /home/e05374pc/exomiser/exomiser-cli-14.0.2)
2024-11-27T11:34:45.659Z  INFO 2030681 --- [           main] o.monarchinitiative.exomiser.cli.Main    : No active profile set, falling back to 1 default profile: "default"
2024-11-27T11:34:46.246Z  INFO 2030681 --- [           main] o.m.exomiser.cli.config.MainConfig       : Exomiser home: /home/e05374pc/exomiser/exomiser-cli-14.0.2
2024-11-27T11:34:46.258Z  INFO 2030681 --- [           main] o.m.exomiser.cli.config.MainConfig       : Root data source directory set to: /home/e05374pc/exomiser/exomiser-cli-14.0.2/data
2024-11-27T11:34:46.261Z  INFO 2030681 --- [           main] o.m.e.c.g.j.JannovarDataProtoSerialiser  : Deserialising Jannovar data from /home/e05374pc/exomiser/exomiser-cli-14.0.2/data/2406_hg38/2406_hg38_transcripts_refseq.ser
2024-11-27T11:34:48.241Z  INFO 2030681 --- [           main] o.m.e.c.g.j.JannovarDataProtoSerialiser  : Deserialisation took 1.98 sec.
2024-11-27T11:34:49.098Z  INFO 2030681 --- [           main] o.m.e.c.g.dao.ClinVarWhiteListReader     : Reading ClinVar whitelist...
2024-11-27T11:34:49.104Z  INFO 2030681 --- [           main] o.m.e.c.g.dao.serialisers.MvStoreUtil    : MVMap 'clinvar' opened with 2897469 entries
2024-11-27T11:34:51.648Z  INFO 2030681 --- [           main] o.m.e.c.g.dao.ClinVarWhiteListReader     : Read 238630 ClinVar whitelist variants in 2549 ms
2024-11-27T11:34:51.670Z  INFO 2030681 --- [           main] o.m.e.a.genome.GenomeDataSourceLoader    : Loaded 238630 whitelist variants
2024-11-27T11:34:51.740Z  INFO 2030681 --- [           main] o.m.e.c.g.dao.serialisers.MvStoreUtil    : MVMap 'alleles' opened with 816467174 entries
2024-11-27T11:34:51.753Z  INFO 2030681 --- [           main] o.m.e.c.g.dao.serialisers.MvStoreUtil    : MVMap 'clinvar' opened with 2897469 entries
2024-11-27T11:34:51.983Z  INFO 2030681 --- [           main] g.GenomeAnalysisServiceAutoConfiguration : Configured hg38 genome analysis service
2024-11-27T11:34:52.874Z  INFO 2030681 --- [           main] o.m.exomiser.cli.config.MainConfig       : Default results directory set to: /home/e05374pc/exomiser/exomiser-cli-14.0.2/results
2024-11-27T11:34:52.888Z  INFO 2030681 --- [           main] o.m.e.a.ExomiserConfigReporter           : exomiser.data-directory: /home/e05374pc/exomiser/exomiser-cli-14.0.2/data
2024-11-27T11:34:52.888Z  INFO 2030681 --- [           main] o.m.e.a.ExomiserConfigReporter           : exomiser.hg19.data-version: -
2024-11-27T11:34:52.888Z  INFO 2030681 --- [           main] o.m.e.a.ExomiserConfigReporter           : exomiser.hg38.data-version: 2406
2024-11-27T11:34:52.888Z  INFO 2030681 --- [           main] o.m.e.a.ExomiserConfigReporter           : exomiser.hg38.clinvar-data-version: 2406
2024-11-27T11:34:52.888Z  INFO 2030681 --- [           main] o.m.e.a.ExomiserConfigReporter           : exomiser.phenotype.data-version: 2406
2024-11-27T11:34:53.006Z  INFO 2030681 --- [           main] o.monarchinitiative.exomiser.cli.Main    : Started Main in 7.578 seconds (process running for 7.773)
2024-11-27T11:34:53.141Z  INFO 2030681 --- [           main] .s.b.a.l.ConditionEvaluationReportLogger : 

Error starting ApplicationContext. To display the condition evaluation report re-run your application with 'debug' enabled.
2024-11-27T11:34:53.175Z ERROR 2030681 --- [           main] o.s.boot.SpringApplication               : Application run failed

java.lang.IllegalArgumentException: Unable to parse sample from file examples/test-analysis-multisample.yml please check the format
        at org.monarchinitiative.exomiser.cli.CommandLineJobReader.readSampleJob(CommandLineJobReader.java:351) ~[exomiser-cli-14.0.2.jar:na]
        at org.monarchinitiative.exomiser.cli.CommandLineJobReader.handleSampleOption(CommandLineJobReader.java:200) ~[exomiser-cli-14.0.2.jar:na]
        at org.monarchinitiative.exomiser.cli.CommandLineJobReader.handleMultipleUserOptions(CommandLineJobReader.java:118) ~[exomiser-cli-14.0.2.jar:na]
        at org.monarchinitiative.exomiser.cli.CommandLineJobReader.readJobs(CommandLineJobReader.java:102) ~[exomiser-cli-14.0.2.jar:na]
        at org.monarchinitiative.exomiser.cli.ExomiserCommandLineRunner.run(ExomiserCommandLineRunner.java:58) ~[exomiser-cli-14.0.2.jar:na]
        at org.springframework.boot.SpringApplication.lambda$callRunner$5(SpringApplication.java:790) ~[spring-boot-3.2.3.jar:3.2.3]
        at org.springframework.util.function.ThrowingConsumer$1.acceptWithException(ThrowingConsumer.java:83) ~[spring-core-6.1.4.jar:6.1.4]
        at org.springframework.util.function.ThrowingConsumer.accept(ThrowingConsumer.java:60) ~[spring-core-6.1.4.jar:6.1.4]
        at org.springframework.util.function.ThrowingConsumer$1.accept(ThrowingConsumer.java:88) ~[spring-core-6.1.4.jar:6.1.4]
        at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:798) ~[spring-boot-3.2.3.jar:3.2.3]
        at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:789) ~[spring-boot-3.2.3.jar:3.2.3]
        at org.springframework.boot.SpringApplication.lambda$callRunners$3(SpringApplication.java:774) ~[spring-boot-3.2.3.jar:3.2.3]
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[na:na]
        at java.base/java.util.stream.SortedOps$SizedRefSortingSink.end(SortedOps.java:357) ~[na:na]
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:510) ~[na:na]
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[na:na]
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[na:na]
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[na:na]
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:na]
        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[na:na]
        at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:774) ~[spring-boot-3.2.3.jar:3.2.3]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:341) ~[spring-boot-3.2.3.jar:3.2.3]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1354) ~[spring-boot-3.2.3.jar:3.2.3]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1343) ~[spring-boot-3.2.3.jar:3.2.3]
        at org.monarchinitiative.exomiser.cli.Main.main(Main.java:53) ~[exomiser-cli-14.0.2.jar:na]
```

I have tried with the phenopacket-based preset files, the standard preset files and my own job files

Running like this

```
java -jar exomiser-cli-14.0.2.jar --sample examples/test-analysis-multisample.yml
```

app.properties are

```
#
# The Exomiser - A tool to annotate and prioritize genomic variants
#
# Copyright (c) 2016-2021 Queen Mary University of London.
# Copyright (c) 2012-2016 CharitÃ© UniversitÃ¤tsmedizin Berlin and Genome Research Ltd.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

## exomiser root data directory ##
# root path where data is to be downloaded and worked on. It is assumed that all the files required by exomiser listed
# in this properties file will be found in the data directory, unless specifically overridden here. Exomiser will default
# to using a directory named 'data' in the installation directory, however it is often a good idea to specify the full
# system path as this will allow the data to be installed in a different directory to the application.
exomiser.data-directory=/home/e05374pc/exomiser/exomiser-cli-14.0.2/data

## optional data sources ##
# The location of these files need to be specified for each assembly in the sections below
# REMM can be downloaded from https://zenodo.org/record/4768448
# REMM is required for the genome preset.
# remm.version=0.3.1.post1
# CADD can be downloaded from http://cadd.gs.washington.edu/download
# CADD is an optional datasource
# cadd.version=1.4

### hg19 assembly ###
# exomiser.hg19.data-version=2402
# transcript source will default to ensembl. Can define as ucsc/ensembl/refseq
#exomiser.hg19.transcript-source=ensembl
# location of CADD/REMM Tabix files - you will need these for analysis of non-coding variants.
# You will require the tsv.gz and tsv.gz.tbi (tabix) file pairs.
# Un-comment and add the full path to the relevant tsv.gz files if you want to enable these.
#exomiser.hg19.cadd-snv-path=${exomiser.data-directory}/cadd/${cadd.version}/hg19/whole_genome_SNVs.tsv.gz
#exomiser.hg19.cadd-in-del-path=${exomiser.data-directory}/cadd/${cadd.version}/hg19/InDels.tsv.gz
#exomiser.hg19.remm-path=${exomiser.data-directory}/remm/ReMM.v${remm.version}.hg19.tsv.gz
# local frequencies are required to be normalised in the same manner as the input VCF and frequency values must be percentages.
#exomiser.hg19.local-frequency-path=${exomiser.data-directory}/local/local_frequency_test_hg19.tsv.gz
#exomiser.hg19.variant-white-list-path=${exomiser.hg19.data-version}_hg19_clinvar_whitelist.tsv.gz
#exomiser.hg19.clin-var-data-version=2402
#exomiser.hg19.use-clinvar-white-list=true

### hg38 assembly ###
# To enable analysis of samples called against the hg38 assembly copy the hg19 above and just replace the hg19 with hg38
exomiser.hg38.data-version=2406
exomiser.hg38.transcript-source=refseq
#exomiser.hg38.cadd-snv-path=${exomiser.data-directory}/cadd/${cadd.version}/whole_genome_SNVs.tsv.gz
#exomiser.hg38.cadd-in-del-path=${exomiser.data-directory}/cadd/${cadd.version}/InDels.tsv.gz
#exomiser.hg38.remm-path=${exomiser.data-directory}/remm/ReMM.v${remm.version}.hg38.tsv.gz
#exomiser.hg38.local-frequency-path=${exomiser.data-directory}/local/local_frequency_test_hg38.tsv.gz
#exomiser.hg38.variant-white-list-path=${exomiser.hg38.data-version}_hg38_clinvar_whitelist.tsv.gz
#exomiser.hg38.clin-var-data-version=2406
#exomiser.hg38.use-clinvar-white-list=true

### phenotypes ###
exomiser.phenotype.data-version=2406
#exomiser.phenotype.data-directory=${exomiser.data-directory}/${exomiser.phenotype.data-version}_phenotype
# String random walk data file
#exomiser.phenotype.random-walk-file-name=rw_string_10.mv
#exomiser.phenotype.random-walk-index-file-name=rw_string_9_05_id2index.gz

### caching ###
# If you're running exomiser in batch mode there might be some performance benefit if you enable caching. The 'simple'
# option will continue to store data in memory *without* limit - this means for really long-running batch jobs and/or
# whole genomes you may run out of memory.
# If this is likely choose the caffeine option and uncomment spring.cache.caffeine.spec and adjust the cache size
# to your requirements
#none/simple/caffeine
#spring.cache.type=none
#spring.cache.caffeine.spec=maximumSize=60000

### logging ###
# Logging is highly configurable - see https://docs.spring.io/spring-boot/docs/current/reference/html/features.html#features.logging.file-output
#logging.file.name=logs/exomiser.log
logging.level.com.zaxxer.hikari=ERROR
```

**Comment by Peter-J-Freeman** [comment]
Sorry, spotted my mistake in the run command. should have been --analysis

**Comment by julesjacobsen** [comment]
> Sorry, spotted my mistake in the run command. should have been --analysis

Cool. Glad you got it sorted.
